"""EOS GPIO / PWM Studio.

Beginner-first generator for the GPIO_IN, GPIO_OUT and PWM portions of the
EOS Expansion language.  It deliberately emits ordinary .eos source so the
normal editor/linter remains the source of truth.
"""
from __future__ import annotations

import re
from PySide6.QtCore import Qt
from PySide6.QtGui import QFontDatabase
from PySide6.QtWidgets import (
    QApplication, QCheckBox, QComboBox, QDialog, QFormLayout, QGroupBox,
    QHBoxLayout, QLabel, QMessageBox, QPushButton, QSpinBox, QPlainTextEdit,
    QVBoxLayout, QWidget
)

MODES = [
    "GPIO Output — Static",
    "GPIO Output — Blink",
    "PWM — Fixed Level",
    "PWM — Breathe / Fade",
    "GPIO Input — Mirror to Output",
    "GPIO Input — Report to Xbox",
]

MODE_HELP = {
    MODES[0]: "Drive a digital output HIGH or LOW. Optionally let the Xbox control it through a one-byte mailbox register.",
    MODES[1]: "Blink an LED, relay, optocoupler, or other digital output with independent ON/OFF timing.",
    MODES[2]: "Generate continuous PWM at a fixed duty/frequency. Xbox control turns the duty into a live mailbox value.",
    MODES[3]: "Generate a smooth PWM up/down sequence on the PC and compile it into simple EOS PWM + DELAY instructions.",
    MODES[4]: "Read one GPIO input and mirror its state onto a second GPIO output. Useful for buttons, switches, or passthrough logic.",
    MODES[5]: "Sample a GPIO input and publish the current 0/1 state into the EOS mailbox for an Xbox-side app to read.",
}


def _valid_name(s: str) -> str:
    s = re.sub(r"[^A-Za-z0-9_]", "_", (s or "").strip())
    if not s: s = "LEVEL"
    if s[0].isdigit(): s = "R_" + s
    return s.upper()[:24]


def usable_pins(target: str):
    return [f"EXP{i}" for i in range(4, 9)] if target.upper() == "HD" else [f"EXP{i}" for i in range(1, 9)]


def generate_gpio_script(*, target="NOHD", mode=MODES[1], pin="EXP7", second_pin="EXP8",
                         init=0, safe=0, static_value=1, on_ms=500, off_ms=500,
                         duty=128, freq=1000, period_ms=1800, steps=12,
                         poll_ms=20, xbox_control=False, reg_name="level") -> str:
    target = target.upper()
    reg = _valid_name(reg_name)
    lines = [
        "# Generated by EOS GPIO / PWM Studio",
        f"TARGET {target}",
    ]

    if mode == MODES[0]:
        lines.append(f"USES {pin} AS GPIO_OUT INIT {init} SAFE {safe}")
        if xbox_control:
            lines += [f"  REG {reg.lower()} WIDTH 1", f"DEF {reg} 0x02", "", "LOOP",
                      f"  GETMAIL {reg} R0", f"  SET {pin} R0", f"  DELAY {poll_ms}", "ENDLOOP", "END"]
        else:
            lines += ["", "LOOP", f"  SET {pin} {1 if static_value else 0}", "  DELAY 1000", "ENDLOOP", "END"]

    elif mode == MODES[1]:
        lines += [f"USES {pin} AS GPIO_OUT INIT {init} SAFE {safe}", "", "LOOP",
                  f"  SET {pin} 1", f"  DELAY {on_ms}", f"  SET {pin} 0", f"  DELAY {off_ms}", "ENDLOOP", "END"]

    elif mode == MODES[2]:
        lines.append(f"USES {pin} AS PWM INIT {init} SAFE {safe}")
        if xbox_control:
            lines += [f"  REG {reg.lower()} WIDTH 1", f"DEF {reg} 0x02", "", "LOOP",
                      f"  GETMAIL {reg} R0", f"  PWM {pin} R0 {freq}", f"  DELAY {poll_ms}", "ENDLOOP", "END"]
        else:
            lines += ["", "LOOP", f"  PWM {pin} {duty} {freq}", "  DELAY 1000", "ENDLOOP", "END"]

    elif mode == MODES[3]:
        steps = max(3, min(32, int(steps)))
        half = [round(i * duty / (steps - 1)) for i in range(steps)]
        seq = half + list(reversed(half[1:-1]))
        delay = max(1, int(period_ms / max(1, len(seq))))
        lines += [f"USES {pin} AS PWM INIT {init} SAFE {safe}", "", "LOOP"]
        for v in seq:
            lines += [f"  PWM {pin} {v} {freq}", f"  DELAY {delay}"]
        lines += ["ENDLOOP", "END"]

    elif mode == MODES[4]:
        lines += [f"USES {pin} AS GPIO_IN", f"USES {second_pin} AS GPIO_OUT INIT {init} SAFE {safe}", "", "LOOP",
                  f"  GET {pin} R0", f"  SET {second_pin} R0", f"  DELAY {poll_ms}", "ENDLOOP", "END"]

    elif mode == MODES[5]:
        lines += [f"USES {pin} AS GPIO_IN", f"  REG {reg.lower()} WIDTH 1", f"DEF {reg} 0x02", "", "LOOP",
                  f"  GET {pin} R0", f"  SETMAIL {reg} R0", f"  DELAY {poll_ms}", "ENDLOOP", "END"]

    return "\n".join(lines).rstrip() + "\n"


class GpioPwmStudioDialog(QDialog):
    def __init__(self, parent=None, target="NOHD"):
        super().__init__(parent)
        self.parent_win = parent
        self.target = target.upper() if target else "NOHD"
        self.setWindowTitle("EOS GPIO / PWM Studio")
        self.resize(950, 700)
        self._build()
        self._apply_theme()
        self.refresh()

    def _build(self):
        root = QVBoxLayout(self)
        title = QLabel("GPIO / PWM Studio")
        title.setStyleSheet("font-size:20px;font-weight:700;")
        sub = QLabel("Build common GPIO and PWM scripts without memorizing EOS syntax. The generated source stays fully editable.")
        sub.setWordWrap(True)
        root.addWidget(title); root.addWidget(sub)

        body = QHBoxLayout(); root.addLayout(body, 1)
        left = QVBoxLayout(); body.addLayout(left, 0)

        g = QGroupBox("1 · Choose a job")
        f = QFormLayout(g)
        self.cb_mode = QComboBox(); self.cb_mode.addItems(MODES)
        self.lbl_help = QLabel(); self.lbl_help.setWordWrap(True); self.lbl_help.setMaximumWidth(340)
        f.addRow("Preset", self.cb_mode); f.addRow(self.lbl_help)
        left.addWidget(g)

        g = QGroupBox("2 · Hardware")
        f = QFormLayout(g)
        self.lbl_target = QLabel(self.target)
        self.cb_pin = QComboBox(); self.cb_pin.addItems(usable_pins(self.target))
        self.cb_pin2 = QComboBox(); self.cb_pin2.addItems(usable_pins(self.target)); self.cb_pin2.setCurrentIndex(min(1, self.cb_pin2.count()-1))
        self.sp_init = QSpinBox(); self.sp_init.setRange(0,1)
        self.sp_safe = QSpinBox(); self.sp_safe.setRange(0,1)
        f.addRow("TARGET", self.lbl_target); f.addRow("Primary pin", self.cb_pin); f.addRow("Second pin", self.cb_pin2)
        f.addRow("INIT", self.sp_init); f.addRow("SAFE", self.sp_safe)
        left.addWidget(g)

        g = QGroupBox("3 · Behavior")
        f = QFormLayout(g)
        self.sp_static = QSpinBox(); self.sp_static.setRange(0,1); self.sp_static.setValue(1)
        self.sp_on = QSpinBox(); self.sp_on.setRange(1,65535); self.sp_on.setValue(500); self.sp_on.setSuffix(" ms")
        self.sp_off = QSpinBox(); self.sp_off.setRange(1,65535); self.sp_off.setValue(500); self.sp_off.setSuffix(" ms")
        self.sp_duty = QSpinBox(); self.sp_duty.setRange(0,255); self.sp_duty.setValue(180)
        self.sp_freq = QSpinBox(); self.sp_freq.setRange(1,100000); self.sp_freq.setValue(1000); self.sp_freq.setSuffix(" Hz")
        self.sp_period = QSpinBox(); self.sp_period.setRange(100,65535); self.sp_period.setValue(1800); self.sp_period.setSuffix(" ms")
        self.sp_steps = QSpinBox(); self.sp_steps.setRange(3,32); self.sp_steps.setValue(12)
        self.sp_poll = QSpinBox(); self.sp_poll.setRange(1,1000); self.sp_poll.setValue(20); self.sp_poll.setSuffix(" ms")
        f.addRow("Static value", self.sp_static); f.addRow("ON time", self.sp_on); f.addRow("OFF time", self.sp_off)
        f.addRow("Max / fixed duty", self.sp_duty); f.addRow("PWM frequency", self.sp_freq)
        f.addRow("Breathe period", self.sp_period); f.addRow("Fade steps", self.sp_steps); f.addRow("Poll interval", self.sp_poll)
        left.addWidget(g)

        g = QGroupBox("4 · Optional Xbox control")
        f = QFormLayout(g)
        self.ck_xbox = QCheckBox("Expose a live mailbox value")
        self.ed_reg = QComboBox(); self.ed_reg.setEditable(True); self.ed_reg.addItems(["level", "brightness", "state"])
        f.addRow(self.ck_xbox); f.addRow("Register name", self.ed_reg)
        left.addWidget(g)
        left.addStretch(1)

        right = QVBoxLayout(); body.addLayout(right, 1)
        hdr = QHBoxLayout(); hdr.addWidget(QLabel("Generated EOS script")); hdr.addStretch(1)
        self.lbl_status = QLabel(); hdr.addWidget(self.lbl_status); right.addLayout(hdr)
        self.preview = QPlainTextEdit(); self.preview.setReadOnly(True)
        mono = QFontDatabase.systemFont(QFontDatabase.FixedFont); mono.setPointSize(11); self.preview.setFont(mono)
        right.addWidget(self.preview, 1)

        buttons = QHBoxLayout(); buttons.addStretch(1)
        bcopy = QPushButton("Copy Script"); bcopy.clicked.connect(self.copy_code)
        bopen = QPushButton("Open as New Tab"); bopen.clicked.connect(self.open_new)
        bclose = QPushButton("Close"); bclose.clicked.connect(self.reject)
        buttons.addWidget(bcopy); buttons.addWidget(bopen); buttons.addWidget(bclose); root.addLayout(buttons)

        self.cb_mode.currentTextChanged.connect(self.refresh)
        for w in [self.cb_pin, self.cb_pin2, self.sp_init, self.sp_safe, self.sp_static, self.sp_on, self.sp_off,
                  self.sp_duty, self.sp_freq, self.sp_period, self.sp_steps, self.sp_poll, self.ck_xbox, self.ed_reg]:
            if isinstance(w, QComboBox): w.currentTextChanged.connect(self.refresh)
            elif isinstance(w, QCheckBox): w.toggled.connect(self.refresh)
            else: w.valueChanged.connect(self.refresh)

    def _code(self):
        return generate_gpio_script(
            target=self.target, mode=self.cb_mode.currentText(), pin=self.cb_pin.currentText(), second_pin=self.cb_pin2.currentText(),
            init=self.sp_init.value(), safe=self.sp_safe.value(), static_value=self.sp_static.value(), on_ms=self.sp_on.value(),
            off_ms=self.sp_off.value(), duty=self.sp_duty.value(), freq=self.sp_freq.value(), period_ms=self.sp_period.value(),
            steps=self.sp_steps.value(), poll_ms=self.sp_poll.value(), xbox_control=self.ck_xbox.isChecked(),
            reg_name=self.ed_reg.currentText())

    def refresh(self, *_):
        mode = self.cb_mode.currentText(); self.lbl_help.setText(MODE_HELP[mode])
        is_gpio_out = mode in (MODES[0], MODES[1], MODES[4])
        is_pwm = mode in (MODES[2], MODES[3])
        mirror = mode == MODES[4]
        report = mode == MODES[5]
        self.cb_pin2.setEnabled(mirror)
        self.sp_init.setEnabled(is_gpio_out or is_pwm); self.sp_safe.setEnabled(is_gpio_out or is_pwm)
        self.sp_static.setEnabled(mode == MODES[0]); self.sp_on.setEnabled(mode == MODES[1]); self.sp_off.setEnabled(mode == MODES[1])
        self.sp_duty.setEnabled(is_pwm); self.sp_freq.setEnabled(is_pwm)
        self.sp_period.setEnabled(mode == MODES[3]); self.sp_steps.setEnabled(mode == MODES[3])
        self.sp_poll.setEnabled(mode in (MODES[0], MODES[2], MODES[4], MODES[5]))
        self.ck_xbox.setEnabled(mode in (MODES[0], MODES[2])); self.ed_reg.setEnabled(self.ck_xbox.isChecked() or report)
        warning = ""
        if mirror and self.cb_pin.currentText() == self.cb_pin2.currentText(): warning = "⚠ choose two different pins"
        self.lbl_status.setText(warning or "✓ ready")
        self.lbl_status.setStyleSheet("color:#ff8a80;" if warning else "color:#7ee787;")
        self.preview.setPlainText(self._code())

    def _blocked(self):
        if self.cb_mode.currentText() == MODES[4] and self.cb_pin.currentText() == self.cb_pin2.currentText():
            QMessageBox.warning(self, "Pin conflict", "Input Mirror needs two different expansion pins."); return True
        return False

    def copy_code(self):
        if self._blocked(): return
        QApplication.clipboard().setText(self._code())
        QMessageBox.information(self, "Copied", "GPIO / PWM script copied to the clipboard.")

    def open_new(self):
        if self._blocked(): return
        if self.parent_win and hasattr(self.parent_win, "add_tab"):
            self.parent_win.add_tab(self._code())
            if hasattr(self.parent_win, "run_lint"): self.parent_win.run_lint()
            self.accept()
        else:
            self.copy_code()

    def _apply_theme(self):
        self.setStyleSheet("""
            QDialog, QWidget { background:#10161c; color:#d5dde2; }
            QGroupBox { border:1px solid #2b3942; border-radius:6px; margin-top:8px; padding-top:8px; font-weight:600; }
            QGroupBox::title { subcontrol-origin:margin; left:10px; padding:0 4px; }
            QPlainTextEdit { background:#111a21; border:1px solid #2b3942; border-radius:4px; }
            QComboBox, QSpinBox { background:#182129; border:1px solid #3b4c57; padding:5px; border-radius:4px; }
            QPushButton { background:#25343e; border:1px solid #41545f; padding:7px 11px; border-radius:4px; }
            QPushButton:hover { background:#324650; }
        """)
