"""EOS I2C Studio.

Provides a beginner quick-recipe generator plus a doorbell/mailbox command builder.
All output is plain EOS source and is intended to be opened in the main editor/linter.
"""
from __future__ import annotations

import re
from dataclasses import dataclass
from PySide6.QtCore import Qt
from PySide6.QtGui import QFontDatabase
from PySide6.QtWidgets import (
    QApplication, QComboBox, QDialog, QFormLayout, QGroupBox, QHBoxLayout,
    QHeaderView, QLabel, QLineEdit, QMessageBox, QPushButton, QSpinBox,
    QPlainTextEdit, QTabWidget, QTableWidget, QTableWidgetItem, QVBoxLayout, QWidget
)


def usable_pins(target: str):
    return [f"EXP{i}" for i in range(4, 9)] if target.upper() == "HD" else [f"EXP{i}" for i in range(1, 9)]


def clean_name(s: str, default="ITEM"):
    s = re.sub(r"[^A-Za-z0-9_]", "_", (s or "").strip())
    if not s: s = default
    if s[0].isdigit(): s = "N_" + s
    return s.upper()[:24]


def parse_hex_bytes(text: str):
    t = re.sub(r"[^0-9A-Fa-f]", "", text or "")
    if len(t) % 2: return None
    if len(t) > 512: return None
    return t.upper()


def generate_simple(*, target="NOHD", scl="EXP5", sda="EXP6", dev_name="DEVICE", addr=0x40,
                    recipe="Write + Read Loop", write_hex="0180", read_len=2, dest=0x20, interval=100):
    dev = clean_name(dev_name, "DEVICE")
    payload = parse_hex_bytes(write_hex)
    lines = ["# Generated by EOS I2C Studio — Quick Recipe", f"TARGET {target.upper()}",
             f"USES {scl} {sda} AS I2C", f"DEF {dev} 0x{addr:02X}", "DEF RESULT 0xFF"]
    if payload:
        lines += ["", f"DATA tx {payload}"]
    lines += ["", "LOOP"]
    if recipe in ("Write Loop", "Write + Read Loop"):
        if payload: lines.append(f"  I2CW {dev} tx")
    if recipe in ("Read Loop", "Write + Read Loop"):
        lines.append(f"  I2CR {dev} {read_len} 0x{dest:02X}")
    lines += [f"  DELAY {interval}", "ENDLOOP", "END"]
    return "\n".join(lines) + "\n"


@dataclass
class RegDef:
    name: str
    width: int
    offset: int


@dataclass
class CmdDef:
    name: str
    code: int
    op: str
    tx: str
    rx: str
    fixed: str


OPS = ["Write Register", "Read Register", "Write Fixed Bytes", "Write Register + Read Register"]


def build_doorbell_script(*, target, scl, sda, dev_name, addr, poll_ms, regs, cmds):
    dev = clean_name(dev_name, "DEVICE")
    lines = ["# Generated by EOS I2C Studio — Doorbell Command Builder", f"TARGET {target.upper()}",
             f"USES {scl} {sda} AS I2C"]
    for r in regs:
        lines.append(f"  REG {r.name.lower()} WIDTH {r.width}")
    lines += ["", "# Mailbox map for pin-def 0", "DEF CMD0 0x00", "DEF DB0 0x01"]
    for r in regs:
        lines.append(f"DEF {r.name} 0x{r.offset:02X}")
    lines += [f"DEF {dev} 0x{addr:02X}", "DEF RESULT 0xFF", ""]
    for c in cmds:
        lines.append(f"DEF CMD_{c.name} 0x{c.code:02X}")

    data_defs = []
    handlers = []
    regmap = {r.name: r for r in regs}
    for c in cmds:
        acts = []
        if c.op in ("Write Register", "Write Register + Read Register"):
            r = regmap.get(c.tx)
            if r: acts.append(f"I2CW {dev} VOL {r.name} {r.width}")
        if c.op == "Write Fixed Bytes":
            hx = parse_hex_bytes(c.fixed) or "00"
            dn = f"payload_{c.name.lower()}"
            data_defs.append((dn, hx)); acts.append(f"I2CW {dev} {dn}")
        if c.op in ("Read Register", "Write Register + Read Register"):
            r = regmap.get(c.rx)
            if r: acts.append(f"I2CR {dev} {r.width} {r.name}")
        if not acts: acts = ["NOP"]
        handlers.append((c, acts))

    guarded_count = 1  # SETMAIL DB0 2
    for _, acts in handlers: guarded_count += 1 + len(acts)  # IFMAIL + action lines
    guarded_count += 2  # READY + small delay

    lines += ["", "LOOP", f"  IFMAIL DB0 EQ 1 {guarded_count}", "    SETMAIL DB0 2"]
    for c, acts in handlers:
        lines.append(f"    IFMAIL CMD0 EQ CMD_{c.name} {len(acts)}")
        for a in acts: lines.append("      " + a)
    lines += ["    SETMAIL DB0 3", "    DELAY 2", f"  DELAY {poll_ms}", "ENDLOOP", "END"]
    if data_defs:
        lines += [""]
        for n, hx in data_defs: lines.append(f"DATA {n} {hx}")
    return "\n".join(lines).rstrip() + "\n"


class I2cStudioDialog(QDialog):
    def __init__(self, parent=None, target="NOHD"):
        super().__init__(parent)
        self.parent_win = parent; self.target = target.upper() if target else "NOHD"
        self.setWindowTitle("EOS I²C Studio"); self.resize(1120, 780)
        self._build(); self._apply_theme(); self.refresh_all()

    def _build(self):
        root = QVBoxLayout(self)
        title = QLabel("I²C Studio"); title.setStyleSheet("font-size:20px;font-weight:700;")
        sub = QLabel("Start with a simple device transaction or build a full Xbox ↔ EOS doorbell command map. Offsets and IFMAIL skip counts are generated for you.")
        sub.setWordWrap(True); root.addWidget(title); root.addWidget(sub)

        bus = QGroupBox("Bus / Device")
        bf = QHBoxLayout(bus)
        pins = usable_pins(self.target)
        self.cb_scl = QComboBox(); self.cb_scl.addItems(pins)
        self.cb_sda = QComboBox(); self.cb_sda.addItems(pins); self.cb_sda.setCurrentIndex(min(1, len(pins)-1))
        self.ed_dev = QLineEdit("DEVICE")
        self.sp_addr = QSpinBox(); self.sp_addr.setRange(0x08,0x77); self.sp_addr.setValue(0x40); self.sp_addr.setDisplayIntegerBase(16); self.sp_addr.setPrefix("0x")
        bf.addWidget(QLabel(f"TARGET {self.target}")); bf.addWidget(QLabel("SCL")); bf.addWidget(self.cb_scl); bf.addWidget(QLabel("SDA")); bf.addWidget(self.cb_sda)
        bf.addWidget(QLabel("Device")); bf.addWidget(self.ed_dev); bf.addWidget(QLabel("7-bit addr")); bf.addWidget(self.sp_addr)
        root.addWidget(bus)

        self.tabs = QTabWidget(); root.addWidget(self.tabs, 1)
        self._build_quick_tab(); self._build_doorbell_tab()

        bottom = QHBoxLayout(); self.lbl_status = QLabel(); bottom.addWidget(self.lbl_status); bottom.addStretch(1)
        bcopy = QPushButton("Copy Script"); bcopy.clicked.connect(self.copy_code)
        bopen = QPushButton("Open as New Tab"); bopen.clicked.connect(self.open_new)
        bclose = QPushButton("Close"); bclose.clicked.connect(self.reject)
        bottom.addWidget(bcopy); bottom.addWidget(bopen); bottom.addWidget(bclose); root.addLayout(bottom)

        self.tabs.currentChanged.connect(self.refresh_all)
        for w in (self.cb_scl, self.cb_sda): w.currentTextChanged.connect(self.refresh_all)
        self.ed_dev.textChanged.connect(self.refresh_all); self.sp_addr.valueChanged.connect(self.refresh_all)

    def _build_quick_tab(self):
        w = QWidget(); lay = QHBoxLayout(w)
        left = QVBoxLayout(); lay.addLayout(left, 0)
        g = QGroupBox("Quick Recipe")
        f = QFormLayout(g)
        self.cb_recipe = QComboBox(); self.cb_recipe.addItems(["Write + Read Loop", "Write Loop", "Read Loop"])
        self.ed_write = QLineEdit("0180"); self.ed_write.setPlaceholderText("compact hex, e.g. 0180")
        self.sp_readlen = QSpinBox(); self.sp_readlen.setRange(1,64); self.sp_readlen.setValue(2)
        self.sp_dest = QSpinBox(); self.sp_dest.setRange(0,0xF7); self.sp_dest.setValue(0x20); self.sp_dest.setDisplayIntegerBase(16); self.sp_dest.setPrefix("0x")
        self.sp_interval = QSpinBox(); self.sp_interval.setRange(1,65535); self.sp_interval.setValue(100); self.sp_interval.setSuffix(" ms")
        f.addRow("Recipe", self.cb_recipe); f.addRow("Write bytes", self.ed_write); f.addRow("Read length", self.sp_readlen)
        f.addRow("Read destination", self.sp_dest); f.addRow("Loop interval", self.sp_interval)
        left.addWidget(g)
        note = QLabel("Tip: for register-based devices, put the register byte first. Example 01 80 writes 0x80 to device register 0x01.")
        note.setWordWrap(True); note.setMaximumWidth(320); left.addWidget(note); left.addStretch(1)
        self.quick_preview = QPlainTextEdit(); self.quick_preview.setReadOnly(True); lay.addWidget(self.quick_preview, 1)
        mono = QFontDatabase.systemFont(QFontDatabase.FixedFont); mono.setPointSize(11); self.quick_preview.setFont(mono)
        for wdg in (self.cb_recipe,): wdg.currentTextChanged.connect(self.refresh_all)
        self.ed_write.textChanged.connect(self.refresh_all); self.sp_readlen.valueChanged.connect(self.refresh_all)
        self.sp_dest.valueChanged.connect(self.refresh_all); self.sp_interval.valueChanged.connect(self.refresh_all)
        self.tabs.addTab(w, "Quick Device")

    def _build_doorbell_tab(self):
        w = QWidget(); lay = QHBoxLayout(w)
        left = QVBoxLayout(); lay.addLayout(left, 1)

        rg = QGroupBox("Mailbox Registers")
        rv = QVBoxLayout(rg)
        self.tbl_regs = QTableWidget(0,3); self.tbl_regs.setHorizontalHeaderLabels(["Name", "Width", "Offset"])
        self.tbl_regs.horizontalHeader().setSectionResizeMode(0,QHeaderView.Stretch); self.tbl_regs.horizontalHeader().setSectionResizeMode(1,QHeaderView.ResizeToContents); self.tbl_regs.horizontalHeader().setSectionResizeMode(2,QHeaderView.ResizeToContents)
        rv.addWidget(self.tbl_regs)
        rb = QHBoxLayout(); a=QPushButton("+ Register"); a.clicked.connect(lambda: self.add_reg()); d=QPushButton("− Remove"); d.clicked.connect(self.remove_reg); rb.addWidget(a); rb.addWidget(d); rb.addStretch(1); rv.addLayout(rb)
        left.addWidget(rg, 1)

        cg = QGroupBox("Doorbell Commands")
        cv = QVBoxLayout(cg)
        self.tbl_cmds = QTableWidget(0,6); self.tbl_cmds.setHorizontalHeaderLabels(["Name","Code","Operation","TX Register","RX Register","Fixed Hex"])
        self.tbl_cmds.horizontalHeader().setSectionResizeMode(QHeaderView.Stretch)
        cv.addWidget(self.tbl_cmds)
        cb = QHBoxLayout(); a=QPushButton("+ Command"); a.clicked.connect(lambda: self.add_cmd()); d=QPushButton("− Remove"); d.clicked.connect(self.remove_cmd); cb.addWidget(a); cb.addWidget(d); cb.addStretch(1); cv.addLayout(cb)
        left.addWidget(cg, 1)

        opt = QHBoxLayout(); opt.addWidget(QLabel("Idle poll")); self.sp_poll=QSpinBox(); self.sp_poll.setRange(1,1000); self.sp_poll.setValue(10); self.sp_poll.setSuffix(" ms"); opt.addWidget(self.sp_poll); opt.addStretch(1); left.addLayout(opt)

        right = QVBoxLayout(); lay.addLayout(right, 1)
        self.map_view = QPlainTextEdit(); self.map_view.setReadOnly(True); self.map_view.setMaximumHeight(180)
        self.db_preview = QPlainTextEdit(); self.db_preview.setReadOnly(True)
        mono = QFontDatabase.systemFont(QFontDatabase.FixedFont); mono.setPointSize(10); self.map_view.setFont(mono); self.db_preview.setFont(mono)
        right.addWidget(QLabel("Generated mailbox map")); right.addWidget(self.map_view); right.addWidget(QLabel("Generated EOS script")); right.addWidget(self.db_preview,1)

        self.tbl_regs.cellChanged.connect(self.refresh_all); self.tbl_cmds.cellChanged.connect(self.refresh_all); self.sp_poll.valueChanged.connect(self.refresh_all)
        self.tabs.addTab(w, "Doorbell Builder")
        self.add_reg("payload",4); self.add_reg("response",2); self.add_cmd("FORWARD",1,"Write Register","PAYLOAD","",""); self.add_cmd("READ",2,"Read Register","","RESPONSE","")

    def add_reg(self, name="register", width=1):
        self.tbl_regs.blockSignals(True); r=self.tbl_regs.rowCount(); self.tbl_regs.insertRow(r)
        self.tbl_regs.setItem(r,0,QTableWidgetItem(name)); self.tbl_regs.setItem(r,1,QTableWidgetItem(str(width))); off=QTableWidgetItem("auto"); off.setFlags(off.flags() & ~Qt.ItemIsEditable); self.tbl_regs.setItem(r,2,off)
        self.tbl_regs.blockSignals(False); self.refresh_all()
    def remove_reg(self):
        r=self.tbl_regs.currentRow();
        if r>=0: self.tbl_regs.removeRow(r); self.refresh_all()

    def add_cmd(self, name="COMMAND", code=1, op="Write Register", tx="", rx="", fixed=""):
        self.tbl_cmds.blockSignals(True); r=self.tbl_cmds.rowCount(); self.tbl_cmds.insertRow(r)
        self.tbl_cmds.setItem(r,0,QTableWidgetItem(name)); self.tbl_cmds.setItem(r,1,QTableWidgetItem(f"0x{code:02X}"))
        combo=QComboBox(); combo.addItems(OPS); combo.setCurrentText(op); combo.currentTextChanged.connect(self.refresh_all); self.tbl_cmds.setCellWidget(r,2,combo)
        txc=QComboBox(); rxc=QComboBox();
        names=[clean_name(self.tbl_regs.item(i,0).text(), "REG") for i in range(self.tbl_regs.rowCount()) if self.tbl_regs.item(i,0)]
        txc.addItems([""]+names); rxc.addItems([""]+names); txc.setCurrentText(tx); rxc.setCurrentText(rx)
        txc.currentTextChanged.connect(self.refresh_all); rxc.currentTextChanged.connect(self.refresh_all)
        self.tbl_cmds.setCellWidget(r,3,txc); self.tbl_cmds.setCellWidget(r,4,rxc); self.tbl_cmds.setItem(r,5,QTableWidgetItem(fixed))
        self.tbl_cmds.blockSignals(False); self.refresh_all()
    def remove_cmd(self):
        r=self.tbl_cmds.currentRow();
        if r>=0: self.tbl_cmds.removeRow(r); self.refresh_all()

    def _regs(self):
        out=[]; off=2; seen=set(); self.tbl_regs.blockSignals(True)
        for r in range(self.tbl_regs.rowCount()):
            name=clean_name(self.tbl_regs.item(r,0).text() if self.tbl_regs.item(r,0) else "REG", "REG")
            try: width=int(self.tbl_regs.item(r,1).text())
            except Exception: width=1
            width=max(1,min(64,width));
            if name in seen: name=f"{name}_{r+1}"
            seen.add(name); out.append(RegDef(name,width,off))
            self.tbl_regs.setItem(r,2,QTableWidgetItem(f"0x{off:02X}–0x{off+width-1:02X}" if width>1 else f"0x{off:02X}")); self.tbl_regs.item(r,2).setFlags(self.tbl_regs.item(r,2).flags() & ~Qt.ItemIsEditable)
            off += width
        self.tbl_regs.blockSignals(False); return out

    def _sync_reg_combos(self, regs):
        names=[r.name for r in regs]
        for row in range(self.tbl_cmds.rowCount()):
            for col in (3,4):
                cb=self.tbl_cmds.cellWidget(row,col)
                if not isinstance(cb,QComboBox): continue
                cur=cb.currentText(); cb.blockSignals(True); cb.clear(); cb.addItems([""]+names)
                if cur in names: cb.setCurrentText(cur)
                cb.blockSignals(False)

    def _cmds(self):
        out=[]; seen=set()
        for r in range(self.tbl_cmds.rowCount()):
            name=clean_name(self.tbl_cmds.item(r,0).text() if self.tbl_cmds.item(r,0) else "CMD", "CMD")
            if name in seen: name=f"{name}_{r+1}"
            seen.add(name)
            t=(self.tbl_cmds.item(r,1).text() if self.tbl_cmds.item(r,1) else "1").strip()
            try: code=int(t,0)
            except Exception: code=r+1
            code=max(0,min(255,code))
            combo=self.tbl_cmds.cellWidget(r,2); op=combo.currentText() if combo else OPS[0]
            txw=self.tbl_cmds.cellWidget(r,3); rxw=self.tbl_cmds.cellWidget(r,4)
            tx=clean_name(txw.currentText(),"") if txw and txw.currentText().strip() else ""
            rx=clean_name(rxw.currentText(),"") if rxw and rxw.currentText().strip() else ""
            fixed=self.tbl_cmds.item(r,5).text().strip() if self.tbl_cmds.item(r,5) else ""
            out.append(CmdDef(name,code,op,tx,rx,fixed))
        return out

    def _doorbell_code(self):
        return build_doorbell_script(target=self.target,scl=self.cb_scl.currentText(),sda=self.cb_sda.currentText(),dev_name=self.ed_dev.text(),addr=self.sp_addr.value(),poll_ms=self.sp_poll.value(),regs=self._regs(),cmds=self._cmds())

    def _quick_code(self):
        return generate_simple(target=self.target,scl=self.cb_scl.currentText(),sda=self.cb_sda.currentText(),dev_name=self.ed_dev.text(),addr=self.sp_addr.value(),recipe=self.cb_recipe.currentText(),write_hex=self.ed_write.text(),read_len=self.sp_readlen.value(),dest=self.sp_dest.value(),interval=self.sp_interval.value())

    def current_code(self): return self._quick_code() if self.tabs.currentIndex()==0 else self._doorbell_code()

    def refresh_all(self,*_):
        if not hasattr(self,"quick_preview"): return
        self.quick_preview.setPlainText(self._quick_code())
        regs=self._regs();
        if hasattr(self,"tbl_cmds"): self._sync_reg_combos(regs)
        cmds=self._cmds() if hasattr(self,"tbl_cmds") else []
        if hasattr(self,"db_preview"):
            self.db_preview.setPlainText(self._doorbell_code())
            m=["pin-def 0 mailbox", "0x00  CMD", "0x01  DOORBELL   (0 IDLE / 1 PENDING / 2 BUSY / 3 READY)"]
            for r in regs: m.append(f"0x{r.offset:02X}  {r.name:<14} width {r.width}")
            m += ["0xFF  RESULT     (0 OK / 1 NACK_ADDR / 2 NACK_DATA / 3 TIMEOUT / 4 STUCK)", "", "Commands:"]
            for c in cmds: m.append(f"0x{c.code:02X}  {c.name}  → {c.op}")
            m += ["", "Xbox host flow:", "1. Write command registers", "2. Write CMD code", "3. Set DOORBELL = 1 (PENDING)", "4. Wait for DOORBELL = 3 (READY)", "5. Read response registers", "6. Set DOORBELL = 0 (IDLE)"]
            self.map_view.setPlainText("\n".join(m))
        problems=[]
        if self.cb_scl.currentText()==self.cb_sda.currentText(): problems.append("SCL and SDA must use different pins")
        if regs and regs[-1].offset+regs[-1].width>0xF8: problems.append("register map reaches reserved volatile space 0xF8–0xFF")
        if self.tabs.currentIndex()==0:
            if self.cb_recipe.currentText() in ("Write Loop","Write + Read Loop") and parse_hex_bytes(self.ed_write.text()) is None: problems.append("write bytes must be an even number of hex digits (max 256 bytes)")
            if self.cb_recipe.currentText() in ("Read Loop","Write + Read Loop") and self.sp_dest.value()+self.sp_readlen.value()>0xF8: problems.append("read destination would overlap reserved volatile space 0xF8–0xFF")
        if self.tabs.currentIndex()==1:
            rnames={r.name for r in regs}
            codes=[c.code for c in cmds]
            if len(codes)!=len(set(codes)): problems.append("command codes must be unique")
            for c in cmds:
                if c.op in ("Write Register","Write Register + Read Register") and c.tx not in rnames: problems.append(f"{c.name}: choose a valid TX register")
                if c.op in ("Read Register","Write Register + Read Register") and c.rx not in rnames: problems.append(f"{c.name}: choose a valid RX register")
                if c.op=="Write Fixed Bytes" and parse_hex_bytes(c.fixed) is None: problems.append(f"{c.name}: Fixed Hex is invalid")
        # refresh_all() is also used while the default Doorbell rows are being
        # seeded inside _build_doorbell_tab().  At that point the bottom status
        # bar has not been constructed yet, so keep validation state but defer
        # touching the widget until it exists.
        self._problems = problems
        if hasattr(self, "lbl_status"):
            self.lbl_status.setText("⚠ " + problems[0] if problems else "✓ ready")
            self.lbl_status.setStyleSheet("color:#ff8a80;" if problems else "color:#7ee787;")

    def _blocked(self):
        self.refresh_all()
        if self._problems:
            QMessageBox.warning(self,"Fix these first","\n".join("• "+p for p in self._problems)); return True
        return False
    def copy_code(self):
        if self._blocked(): return
        QApplication.clipboard().setText(self.current_code()); QMessageBox.information(self,"Copied","I²C script copied to the clipboard.")
    def open_new(self):
        if self._blocked(): return
        if self.parent_win and hasattr(self.parent_win,"add_tab"):
            self.parent_win.add_tab(self.current_code());
            if hasattr(self.parent_win,"run_lint"): self.parent_win.run_lint()
            self.accept()
        else: self.copy_code()

    def _apply_theme(self):
        self.setStyleSheet("""
            QDialog, QWidget { background:#10161c; color:#d5dde2; }
            QGroupBox { border:1px solid #2b3942; border-radius:6px; margin-top:8px; padding-top:8px; font-weight:600; }
            QGroupBox::title { subcontrol-origin:margin; left:10px; padding:0 4px; }
            QPlainTextEdit, QTableWidget { background:#111a21; border:1px solid #2b3942; border-radius:4px; }
            QLineEdit, QComboBox, QSpinBox { background:#182129; border:1px solid #3b4c57; padding:5px; border-radius:4px; }
            QPushButton { background:#25343e; border:1px solid #41545f; padding:7px 11px; border-radius:4px; }
            QPushButton:hover { background:#324650; }
            QHeaderView::section { background:#1b2730; color:#d5dde2; border:1px solid #2b3942; padding:5px; }
            QTabBar::tab { background:#172129; padding:7px 14px; border:1px solid #2b3942; }
            QTabBar::tab:selected { background:#25343e; }
        """)
