// eos_serve_hud.v -- GENERATED by gen_hud.py.  Maximized colour serve dashboard.
// Panels: title / BOOT-LINK / SERVE / FLASH ENGINE / SDRAM preload /
//         ADDRESS-SPACE SERVE MAP (live) / SERVE LOG x8 / STABILITY.
// 607 active cells on a 160x45 grid.  attr: 0 norm 1 hdr 2 purple 3 grn 4 amb 5 red 7 dim.
module eos_serve_hud (
    input  wire        lclk, lreset_n, vclk,
    input  wire [3:0]  state,
    input  wire [20:0] mem_addr,
    input  wire [3:0]  lad,
    input  wire        mem_valid,
    input  wire        sd_ready,
    input  wire        preload_done,
    input  wire [22:0] filled_lo,
    input  wire [3:0]  bank_sel,
    input  wire [2:0]  flash_op,      // 0 IDLE 1 ERASE 2 WRITE 3 READ 4 SYNC
    // boot-control diagnostics
    input  wire        mode_16,       // 1 = Xbox 1.6
    input  wire        d0_active,     // D0 being pulled low
    input  wire        abort_active,  // LFRAME# abort in progress
    input  wire [15:0] abort_count,
    // Darkone I2C (SMBus slave) engine
    input  wire [7:0]  i2c_addr,      // 8-bit device address (e.g. 0xDC)
    input  wire [7:0]  i2c_vmaj, i2c_vmin, i2c_vpat,   // firmware version
    input  wire [7:0]  i2c_cmd, i2c_a0, i2c_a1,        // last command + args
    input  wire [7:0]  i2c_rx,        // transactions addressed to us
    input  wire        i2c_sel,
    output reg         wr_en,
    output reg  [12:0] wr_addr,
    output reg  [7:0]  wr_data,
    output reg  [2:0]  wr_attr
);
    localparam [2:0] A_OK=3'd3, A_WARN=3'd4, A_FAIL=3'd5;
    localparam READ_DATA0=4'd7, READ_DATA1=4'd8, TAR_EXIT=4'd9, SYNCING=4'd5;
    function [7:0] hx; input [3:0] n; hx=(n<10)?(8'h30+n):(8'h37+n); endfunction
    function [12:0] i32; input integer i; i32=i[12:0]; endfunction

    // ---- sync the async straps/flags into lclk ----
    reg [1:0] m16_s=0, d0_s=0, ab_s=0;
    reg [1:0] sdr_s=0, pld_s=0; reg [4:0] fl_s0=0, fl_s1=0;
    always @(posedge lclk) begin
        m16_s<={m16_s[0],mode_16}; d0_s<={d0_s[0],d0_active}; ab_s<={ab_s[0],abort_active};
        sdr_s<={sdr_s[0],sd_ready}; pld_s<={pld_s[0],preload_done};
        fl_s0<=filled_lo[18:14]; fl_s1<=fl_s0;
    end
    wire mode16_s = m16_s[1], d0on_s = d0_s[1], aborting_s = ab_s[1];
    wire sd_rdy = sdr_s[1], pld = pld_s[1];

    // I2C engine signals -> sync into the VCLK (display) domain.
    reg [7:0] iaddr=0, ivmaj=0, ivmin=0, ivpat=0, icmd=0, ia0=0, ia1=0, irx=0;
    reg [1:0] isel=0;
    always @(posedge vclk) begin
        iaddr<=i2c_addr; ivmaj<=i2c_vmaj; ivmin<=i2c_vmin; ivpat<=i2c_vpat;
        icmd<=i2c_cmd; ia0<=i2c_a0; ia1<=i2c_a1; irx<=i2c_rx;
        isel<={isel[0],i2c_sel};
    end
    wire [7:0] i2c_addr_s=iaddr, i2c_vmaj_s=ivmaj, i2c_vmin_s=ivmin, i2c_vpat_s=ivpat;
    wire [7:0] i2c_cmd_s=icmd, i2c_a0_s=ia0, i2c_a1_s=ia1, i2c_rx_s=irx;
    wire i2c_sel_s=isel[1];

    // ---- serve status capture (lclk) ----
    reg [3:0] prev_state=0, lo_nib=0; reg [7:0] sbyte=0; reg [15:0] rdcnt=0;
    reg [20:0] addr=0; reg [3:0] bank_load=4'h1; reg loaded_cap=0;
    reg [19:0] log0a=0,log1a=0,log2a=0,log3a=0,log4a=0,log5a=0,log6a=0,log7a=0;
    reg [7:0]  log0b=0,log1b=0,log2b=0,log3b=0,log4b=0,log5b=0,log6b=0,log7b=0;
    reg [19:0] faila=0; reg [7:0] failb=0; reg [11:0] resets=0;
    // serve-rate window: reads since the last ~0.06 s tick
    reg [20:0] wtick=0; reg [15:0] rate=0, rdcnt_prev=0;
    // address-space serve heat: 64 chunks of 32 KB over the 2 MB serve window
    reg [63:0] visited=64'd0; wire [5:0] cur_chunk = addr[20:15];

    always @(posedge lclk) begin
        if (!loaded_cap) begin bank_load<=bank_sel; loaded_cap<=1'b1; end
        prev_state<=state;
        if (state==SYNCING)    addr<=mem_addr;
        if (state==READ_DATA0) lo_nib<=lad;
        if (state==READ_DATA1) sbyte<={lad,lo_nib};
        if (prev_state==READ_DATA1 && state==TAR_EXIT) begin
            rdcnt<=rdcnt+1'b1;
            log7a<=log6a;log6a<=log5a;log5a<=log4a;log4a<=log3a;
            log3a<=log2a;log2a<=log1a;log1a<=log0a;log0a<=addr;
            log7b<=log6b;log6b<=log5b;log5b<=log4b;log4b<=log3b;
            log3b<=log2b;log2b<=log1b;log1b<=log0b;log0b<=sbyte;
        end
        if (!lreset_n)                                              // serve-heat: one driver
            visited<=64'd0;
        else if (prev_state==READ_DATA1 && state==TAR_EXIT)
            visited[cur_chunk]<=1'b1;
        wtick<=wtick+1'b1;
        if (&wtick) begin rate<=rdcnt-rdcnt_prev; rdcnt_prev<=rdcnt; end
    end
    always @(negedge lreset_n) begin faila<=log0a; failb<=log0b; resets<=resets+1'b1; end

    // ---- preload bar (32 cells) + percent ----
    wire [23:0] filled24 = {1'b0,filled_lo};
    wire [18:0] filled_val = {fl_s1,14'd0};
    wire [18:0] prog = pld ? 19'h40000 : (19'h40000 - filled_val);
    wire [5:0]  bar32 = pld ? 6'd32 : {1'b0,prog[17:13]};
    wire [25:0] prog100 = prog * 26'd100;
    wire [6:0]  pctv = pld ? 7'd100 : (prog100 >> 18);
    wire [3:0]  pd_h = (pctv>=7'd100)?4'd1:4'd0;
    wire [6:0]  pr1 = (pctv>=7'd100)?(pctv-7'd100):pctv;
    wire [3:0]  pd_t = pr1/7'd10, pd_o = pr1%7'd10;
    wire [11:0] pctd = {pd_h,pd_t,pd_o};

    // ---- named-value strings ----
    wire [7:0] d0w   [0:5];                  // "FORCED" / "REL   "
    assign d0w[0]=d0on_s?"F":"R"; assign d0w[1]=d0on_s?"O":"E"; assign d0w[2]=d0on_s?"R":"L";
    assign d0w[3]=d0on_s?"C":" "; assign d0w[4]=d0on_s?"E":" "; assign d0w[5]=d0on_s?"D":" ";
    wire [2:0] d0a = d0on_s?A_OK:7;
    wire [7:0] lrw  [0:4];                    // "RUN  " / "RST  "
    assign lrw[0]=lreset_n?"R":"R"; assign lrw[1]=lreset_n?"U":"S"; assign lrw[2]=lreset_n?"N":"T";
    assign lrw[3]=" "; assign lrw[4]=" ";
    wire [2:0] lra = lreset_n?A_OK:A_FAIL;
    wire [7:0] sdw  [0:4];                    // "RDY  " / "WAIT "
    assign sdw[0]=sd_rdy?"R":"W"; assign sdw[1]=sd_rdy?"D":"A"; assign sdw[2]=sd_rdy?"Y":"I";
    assign sdw[3]=sd_rdy?" ":"T"; assign sdw[4]=" ";
    wire [2:0] sda = sd_rdy?A_OK:A_WARN;
    // flash op name (5 chars) + colour
    reg [39:0] fops; reg [2:0] fopa; reg fbusy;
    always @(*) begin
        case (flash_op)
            3'd1: begin fops="ERASE"; fopa=A_WARN; fbusy=1; end
            3'd2: begin fops="WRITE"; fopa=A_WARN; fbusy=1; end
            3'd3: begin fops="READ "; fopa=A_OK;   fbusy=1; end
            3'd4: begin fops="SYNC "; fopa=2;      fbusy=1; end
            default: begin fops="IDLE "; fopa=7;   fbusy=0; end
        endcase
    end
    wire [7:0] fopw [0:4];
    assign fopw[0]=fops[39:32]; assign fopw[1]=fops[31:24]; assign fopw[2]=fops[23:16];
    assign fopw[3]=fops[15:8];  assign fopw[4]=fops[7:0];

    // ---- fault word ----
    wire [2:0] fat = (resets>=12'd3)?A_FAIL:(resets!=12'd0)?A_WARN:A_OK;
    function [7:0] fch; input integer p; reg [47:0] s; begin
        if      (resets>=12'd3) s=48'h465241473F20;  // FRAG?
        else if (resets!=12'd0) s=48'h524554525920;  // RETRY
        else                    s=48'h535441424C45;  // STABLE
        fch = s[47-8*p -: 8];
    end endfunction

    // ---- address-space serve map cell helpers ----
    function [7:0] mapch; input integer i; begin
        if (i[5:0]==cur_chunk) mapch=">";
        else if (visited[i[5:0]]) mapch="#";
        else mapch=".";
    end endfunction
    function [2:0] mapat; input integer i; begin
        if (i[5:0]==cur_chunk) mapat=3'd4;       // cursor: amber FG, dark bg
        else if (visited[i[5:0]]) mapat=A_OK;    // served: green FG, dark bg
        else mapat=3'd2;                          // idle:   purple FG, dark bg
    end endfunction

    // ---- cell scan FSM: one cell per vclk ----
    reg [12:0] idx=0, wa; reg [7:0] ch; reg [2:0] at;
    always @(posedge vclk) begin
        wr_en<=1'b1;
        case (idx)
            13'd0: begin wa=13'd1; ch=8'h20; at=3'd1; end
            13'd1: begin wa=13'd2; ch=8'h45; at=3'd1; end
            13'd2: begin wa=13'd3; ch=8'h4F; at=3'd1; end
            13'd3: begin wa=13'd4; ch=8'h53; at=3'd1; end
            13'd4: begin wa=13'd5; ch=8'h20; at=3'd1; end
            13'd5: begin wa=13'd6; ch=8'h20; at=3'd1; end
            13'd6: begin wa=13'd7; ch=8'h4C; at=3'd1; end
            13'd7: begin wa=13'd8; ch=8'h50; at=3'd1; end
            13'd8: begin wa=13'd9; ch=8'h43; at=3'd1; end
            13'd9: begin wa=13'd10; ch=8'h20; at=3'd1; end
            13'd10: begin wa=13'd11; ch=8'h42; at=3'd1; end
            13'd11: begin wa=13'd12; ch=8'h49; at=3'd1; end
            13'd12: begin wa=13'd13; ch=8'h4F; at=3'd1; end
            13'd13: begin wa=13'd14; ch=8'h53; at=3'd1; end
            13'd14: begin wa=13'd15; ch=8'h20; at=3'd1; end
            13'd15: begin wa=13'd16; ch=8'h53; at=3'd1; end
            13'd16: begin wa=13'd17; ch=8'h45; at=3'd1; end
            13'd17: begin wa=13'd18; ch=8'h52; at=3'd1; end
            13'd18: begin wa=13'd19; ch=8'h56; at=3'd1; end
            13'd19: begin wa=13'd20; ch=8'h45; at=3'd1; end
            13'd20: begin wa=13'd21; ch=8'h52; at=3'd1; end
            13'd21: begin wa=13'd22; ch=8'h20; at=3'd1; end
            13'd22: begin wa=13'd24; ch=8'h20; at=3'd2; end
            13'd23: begin wa=13'd25; ch=8'h54; at=3'd2; end
            13'd24: begin wa=13'd26; ch=8'h65; at=3'd2; end
            13'd25: begin wa=13'd27; ch=8'h61; at=3'd2; end
            13'd26: begin wa=13'd28; ch=8'h6D; at=3'd2; end
            13'd27: begin wa=13'd29; ch=8'h20; at=3'd2; end
            13'd28: begin wa=13'd30; ch=8'h52; at=3'd2; end
            13'd29: begin wa=13'd31; ch=8'h65; at=3'd2; end
            13'd30: begin wa=13'd32; ch=8'h73; at=3'd2; end
            13'd31: begin wa=13'd33; ch=8'h75; at=3'd2; end
            13'd32: begin wa=13'd34; ch=8'h72; at=3'd2; end
            13'd33: begin wa=13'd35; ch=8'h67; at=3'd2; end
            13'd34: begin wa=13'd36; ch=8'h65; at=3'd2; end
            13'd35: begin wa=13'd37; ch=8'h6E; at=3'd2; end
            13'd36: begin wa=13'd38; ch=8'h74; at=3'd2; end
            13'd37: begin wa=13'd39; ch=8'h20; at=3'd2; end
            13'd38: begin wa=13'd40; ch=8'h2F; at=3'd2; end
            13'd39: begin wa=13'd41; ch=8'h20; at=3'd2; end
            13'd40: begin wa=13'd42; ch=8'h44; at=3'd2; end
            13'd41: begin wa=13'd43; ch=8'h61; at=3'd2; end
            13'd42: begin wa=13'd44; ch=8'h72; at=3'd2; end
            13'd43: begin wa=13'd45; ch=8'h6B; at=3'd2; end
            13'd44: begin wa=13'd46; ch=8'h6F; at=3'd2; end
            13'd45: begin wa=13'd47; ch=8'h6E; at=3'd2; end
            13'd46: begin wa=13'd48; ch=8'h65; at=3'd2; end
            13'd47: begin wa=13'd49; ch=8'h38; at=3'd2; end
            13'd48: begin wa=13'd50; ch=8'h33; at=3'd2; end
            13'd49: begin wa=13'd51; ch=8'h20; at=3'd2; end
            13'd50: begin wa=13'd321; ch=8'h42; at=3'd2; end
            13'd51: begin wa=13'd322; ch=8'h4F; at=3'd2; end
            13'd52: begin wa=13'd323; ch=8'h4F; at=3'd2; end
            13'd53: begin wa=13'd324; ch=8'h54; at=3'd2; end
            13'd54: begin wa=13'd325; ch=8'h20; at=3'd2; end
            13'd55: begin wa=13'd326; ch=8'h2F; at=3'd2; end
            13'd56: begin wa=13'd327; ch=8'h20; at=3'd2; end
            13'd57: begin wa=13'd328; ch=8'h4C; at=3'd2; end
            13'd58: begin wa=13'd329; ch=8'h49; at=3'd2; end
            13'd59: begin wa=13'd330; ch=8'h4E; at=3'd2; end
            13'd60: begin wa=13'd331; ch=8'h4B; at=3'd2; end
            13'd61: begin wa=13'd481; ch=8'h52; at=3'd0; end
            13'd62: begin wa=13'd482; ch=8'h45; at=3'd0; end
            13'd63: begin wa=13'd483; ch=8'h56; at=3'd0; end
            13'd64: begin wa=13'd487; ch=8'h31; at=3'd2; end
            13'd65: begin wa=13'd488; ch=8'h2E; at=3'd2; end
            13'd66: begin wa=13'd489; ch=mode16_s?"6":"5"; at=(mode16_s?A_WARN:A_OK); end
            13'd67: begin wa=13'd641; ch=8'h44; at=3'd0; end
            13'd68: begin wa=13'd642; ch=8'h30; at=3'd0; end
            13'd69: begin wa=13'd647; ch=8'h20; at=3'd0; end
            13'd70: begin wa=13'd648; ch=8'h20; at=3'd0; end
            13'd71: begin wa=13'd649; ch=8'h20; at=3'd0; end
            13'd72: begin wa=13'd650; ch=8'h20; at=3'd0; end
            13'd73: begin wa=13'd651; ch=8'h20; at=3'd0; end
            13'd74: begin wa=13'd652; ch=8'h20; at=3'd0; end
            13'd75: begin wa=13'd647; ch=d0w[0]; at=(d0a); end
            13'd76: begin wa=13'd648; ch=d0w[1]; at=(d0a); end
            13'd77: begin wa=13'd649; ch=d0w[2]; at=(d0a); end
            13'd78: begin wa=13'd650; ch=d0w[3]; at=(d0a); end
            13'd79: begin wa=13'd651; ch=d0w[4]; at=(d0a); end
            13'd80: begin wa=13'd652; ch=d0w[5]; at=(d0a); end
            13'd81: begin wa=13'd801; ch=8'h4C; at=3'd0; end
            13'd82: begin wa=13'd802; ch=8'h46; at=3'd0; end
            13'd83: begin wa=13'd803; ch=8'h52; at=3'd0; end
            13'd84: begin wa=13'd804; ch=8'h41; at=3'd0; end
            13'd85: begin wa=13'd805; ch=8'h4D; at=3'd0; end
            13'd86: begin wa=13'd806; ch=8'h45; at=3'd0; end
            13'd87: begin wa=13'd807; ch=8'h20; at=3'd0; end
            13'd88: begin wa=13'd808; ch=8'h41; at=3'd0; end
            13'd89: begin wa=13'd809; ch=8'h42; at=3'd0; end
            13'd90: begin wa=13'd810; ch=8'h4F; at=3'd0; end
            13'd91: begin wa=13'd811; ch=8'h52; at=3'd0; end
            13'd92: begin wa=13'd812; ch=8'h54; at=3'd0; end
            13'd93: begin wa=13'd813; ch=8'h53; at=3'd0; end
            13'd94: begin wa=13'd815; ch=hx(abort_count[15:12]); at=3'd4; end
            13'd95: begin wa=13'd816; ch=hx(abort_count[11:8]); at=3'd4; end
            13'd96: begin wa=13'd817; ch=hx(abort_count[7:4]); at=3'd4; end
            13'd97: begin wa=13'd818; ch=hx(abort_count[3:0]); at=3'd4; end
            13'd98: begin wa=13'd820; ch=aborting_s?"*":" "; at=(A_FAIL); end
            13'd99: begin wa=13'd961; ch=8'h4C; at=3'd0; end
            13'd100: begin wa=13'd962; ch=8'h43; at=3'd0; end
            13'd101: begin wa=13'd963; ch=8'h4C; at=3'd0; end
            13'd102: begin wa=13'd964; ch=8'h4B; at=3'd0; end
            13'd103: begin wa=13'd967; ch=8'h5B; at=3'd3; end
            13'd104: begin wa=13'd968; ch=8'h20; at=3'd3; end
            13'd105: begin wa=13'd969; ch=8'h4F; at=3'd3; end
            13'd106: begin wa=13'd970; ch=8'h4B; at=3'd3; end
            13'd107: begin wa=13'd971; ch=8'h20; at=3'd3; end
            13'd108: begin wa=13'd972; ch=8'h5D; at=3'd3; end
            13'd109: begin wa=13'd1121; ch=8'h4C; at=3'd0; end
            13'd110: begin wa=13'd1122; ch=8'h52; at=3'd0; end
            13'd111: begin wa=13'd1123; ch=8'h45; at=3'd0; end
            13'd112: begin wa=13'd1124; ch=8'h53; at=3'd0; end
            13'd113: begin wa=13'd1125; ch=8'h45; at=3'd0; end
            13'd114: begin wa=13'd1126; ch=8'h54; at=3'd0; end
            13'd115: begin wa=13'd1127; ch=lrw[0]; at=(lra); end
            13'd116: begin wa=13'd1128; ch=lrw[1]; at=(lra); end
            13'd117: begin wa=13'd1129; ch=lrw[2]; at=(lra); end
            13'd118: begin wa=13'd1130; ch=lrw[3]; at=(lra); end
            13'd119: begin wa=13'd1131; ch=lrw[4]; at=(lra); end
            13'd120: begin wa=13'd360; ch=8'h53; at=3'd2; end
            13'd121: begin wa=13'd361; ch=8'h45; at=3'd2; end
            13'd122: begin wa=13'd362; ch=8'h52; at=3'd2; end
            13'd123: begin wa=13'd363; ch=8'h56; at=3'd2; end
            13'd124: begin wa=13'd364; ch=8'h45; at=3'd2; end
            13'd125: begin wa=13'd520; ch=8'h42; at=3'd0; end
            13'd126: begin wa=13'd521; ch=8'h41; at=3'd0; end
            13'd127: begin wa=13'd522; ch=8'h4E; at=3'd0; end
            13'd128: begin wa=13'd523; ch=8'h4B; at=3'd0; end
            13'd129: begin wa=13'd526; ch=hx(bank_load[3:0]); at=3'd3; end
            13'd130: begin wa=13'd527; ch=8'h2F; at=3'd0; end
            13'd131: begin wa=13'd528; ch=hx(bank_sel[3:0]); at=3'd1; end
            13'd132: begin wa=13'd680; ch=8'h53; at=3'd0; end
            13'd133: begin wa=13'd681; ch=8'h54; at=3'd0; end
            13'd134: begin wa=13'd682; ch=8'h41; at=3'd0; end
            13'd135: begin wa=13'd683; ch=8'h54; at=3'd0; end
            13'd136: begin wa=13'd684; ch=8'h45; at=3'd0; end
            13'd137: begin wa=13'd686; ch=hx(state[3:0]); at=3'd0; end
            13'd138: begin wa=13'd840; ch=8'h52; at=3'd0; end
            13'd139: begin wa=13'd841; ch=8'h45; at=3'd0; end
            13'd140: begin wa=13'd842; ch=8'h41; at=3'd0; end
            13'd141: begin wa=13'd843; ch=8'h44; at=3'd0; end
            13'd142: begin wa=13'd844; ch=8'h53; at=3'd0; end
            13'd143: begin wa=13'd846; ch=hx(rdcnt[15:12]); at=3'd0; end
            13'd144: begin wa=13'd847; ch=hx(rdcnt[11:8]); at=3'd0; end
            13'd145: begin wa=13'd848; ch=hx(rdcnt[7:4]); at=3'd0; end
            13'd146: begin wa=13'd849; ch=hx(rdcnt[3:0]); at=3'd0; end
            13'd147: begin wa=13'd1000; ch=8'h52; at=3'd0; end
            13'd148: begin wa=13'd1001; ch=8'h41; at=3'd0; end
            13'd149: begin wa=13'd1002; ch=8'h54; at=3'd0; end
            13'd150: begin wa=13'd1003; ch=8'h45; at=3'd0; end
            13'd151: begin wa=13'd1006; ch=hx(rate[15:12]); at=3'd3; end
            13'd152: begin wa=13'd1007; ch=hx(rate[11:8]); at=3'd3; end
            13'd153: begin wa=13'd1008; ch=hx(rate[7:4]); at=3'd3; end
            13'd154: begin wa=13'd1009; ch=hx(rate[3:0]); at=3'd3; end
            13'd155: begin wa=13'd1160; ch=8'h4C; at=3'd0; end
            13'd156: begin wa=13'd1161; ch=8'h41; at=3'd0; end
            13'd157: begin wa=13'd1162; ch=8'h53; at=3'd0; end
            13'd158: begin wa=13'd1163; ch=8'h54; at=3'd0; end
            13'd159: begin wa=13'd1166; ch=hx(addr[19:16]); at=3'd2; end
            13'd160: begin wa=13'd1167; ch=hx(addr[15:12]); at=3'd2; end
            13'd161: begin wa=13'd1168; ch=hx(addr[11:8]); at=3'd2; end
            13'd162: begin wa=13'd1169; ch=hx(addr[7:4]); at=3'd2; end
            13'd163: begin wa=13'd1170; ch=hx(addr[3:0]); at=3'd2; end
            13'd164: begin wa=13'd1171; ch=8'h3A; at=3'd0; end
            13'd165: begin wa=13'd1172; ch=hx(sbyte[7:4]); at=3'd1; end
            13'd166: begin wa=13'd1173; ch=hx(sbyte[3:0]); at=3'd1; end
            13'd167: begin wa=13'd402; ch=8'h46; at=3'd2; end
            13'd168: begin wa=13'd403; ch=8'h4C; at=3'd2; end
            13'd169: begin wa=13'd404; ch=8'h41; at=3'd2; end
            13'd170: begin wa=13'd405; ch=8'h53; at=3'd2; end
            13'd171: begin wa=13'd406; ch=8'h48; at=3'd2; end
            13'd172: begin wa=13'd407; ch=8'h20; at=3'd2; end
            13'd173: begin wa=13'd408; ch=8'h45; at=3'd2; end
            13'd174: begin wa=13'd409; ch=8'h4E; at=3'd2; end
            13'd175: begin wa=13'd410; ch=8'h47; at=3'd2; end
            13'd176: begin wa=13'd411; ch=8'h49; at=3'd2; end
            13'd177: begin wa=13'd412; ch=8'h4E; at=3'd2; end
            13'd178: begin wa=13'd413; ch=8'h45; at=3'd2; end
            13'd179: begin wa=13'd562; ch=8'h4F; at=3'd0; end
            13'd180: begin wa=13'd563; ch=8'h50; at=3'd0; end
            13'd181: begin wa=13'd568; ch=fopw[0]; at=(fopa); end
            13'd182: begin wa=13'd569; ch=fopw[1]; at=(fopa); end
            13'd183: begin wa=13'd570; ch=fopw[2]; at=(fopa); end
            13'd184: begin wa=13'd571; ch=fopw[3]; at=(fopa); end
            13'd185: begin wa=13'd572; ch=fopw[4]; at=(fopa); end
            13'd186: begin wa=13'd722; ch=8'h42; at=3'd0; end
            13'd187: begin wa=13'd723; ch=8'h55; at=3'd0; end
            13'd188: begin wa=13'd724; ch=8'h53; at=3'd0; end
            13'd189: begin wa=13'd725; ch=8'h59; at=3'd0; end
            13'd190: begin wa=13'd728; ch=fbusy?"Y":"-"; at=(fbusy?A_WARN:7); end
            13'd191: begin wa=13'd1042; ch=8'h49; at=3'd2; end
            13'd192: begin wa=13'd1043; ch=8'h32; at=3'd2; end
            13'd193: begin wa=13'd1044; ch=8'h43; at=3'd2; end
            13'd194: begin wa=13'd1045; ch=8'h20; at=3'd2; end
            13'd195: begin wa=13'd1046; ch=8'h45; at=3'd2; end
            13'd196: begin wa=13'd1047; ch=8'h4E; at=3'd2; end
            13'd197: begin wa=13'd1048; ch=8'h47; at=3'd2; end
            13'd198: begin wa=13'd1049; ch=8'h49; at=3'd2; end
            13'd199: begin wa=13'd1050; ch=8'h4E; at=3'd2; end
            13'd200: begin wa=13'd1051; ch=8'h45; at=3'd2; end
            13'd201: begin wa=13'd1060; ch=8'h53; at=3'd0; end
            13'd202: begin wa=13'd1061; ch=8'h45; at=3'd0; end
            13'd203: begin wa=13'd1062; ch=8'h4C; at=3'd0; end
            13'd204: begin wa=13'd1064; ch=i2c_sel_s ? "*" : "-"; at=(i2c_sel_s ? A_OK : 3'd7); end
            13'd205: begin wa=13'd1202; ch=8'h41; at=3'd0; end
            13'd206: begin wa=13'd1203; ch=8'h44; at=3'd0; end
            13'd207: begin wa=13'd1204; ch=8'h44; at=3'd0; end
            13'd208: begin wa=13'd1205; ch=8'h52; at=3'd0; end
            13'd209: begin wa=13'd1206; ch=8'h20; at=3'd0; end
            13'd210: begin wa=13'd1207; ch=8'h30; at=3'd0; end
            13'd211: begin wa=13'd1208; ch=8'h78; at=3'd0; end
            13'd212: begin wa=13'd1209; ch=hx(i2c_addr_s[7:4]); at=3'd0; end
            13'd213: begin wa=13'd1210; ch=hx(i2c_addr_s[3:0]); at=3'd0; end
            13'd214: begin wa=13'd1214; ch=8'h56; at=3'd0; end
            13'd215: begin wa=13'd1215; ch=8'h45; at=3'd0; end
            13'd216: begin wa=13'd1216; ch=8'h52; at=3'd0; end
            13'd217: begin wa=13'd1217; ch=8'h20; at=3'd0; end
            13'd218: begin wa=13'd1218; ch=8'h30+i2c_vmaj_s; at=(0); end
            13'd219: begin wa=13'd1219; ch=8'h2E; at=3'd0; end
            13'd220: begin wa=13'd1220; ch=8'h30+i2c_vmin_s; at=(0); end
            13'd221: begin wa=13'd1221; ch=8'h2E; at=3'd0; end
            13'd222: begin wa=13'd1222; ch=8'h30+i2c_vpat_s; at=(0); end
            13'd223: begin wa=13'd1362; ch=8'h43; at=3'd0; end
            13'd224: begin wa=13'd1363; ch=8'h4D; at=3'd0; end
            13'd225: begin wa=13'd1364; ch=8'h44; at=3'd0; end
            13'd226: begin wa=13'd1365; ch=8'h20; at=3'd0; end
            13'd227: begin wa=13'd1366; ch=8'h30; at=3'd0; end
            13'd228: begin wa=13'd1367; ch=8'h78; at=3'd0; end
            13'd229: begin wa=13'd1368; ch=hx(i2c_cmd_s[7:4]); at=3'd3; end
            13'd230: begin wa=13'd1369; ch=hx(i2c_cmd_s[3:0]); at=3'd3; end
            13'd231: begin wa=13'd1372; ch=8'h41; at=3'd0; end
            13'd232: begin wa=13'd1373; ch=8'h30; at=3'd0; end
            13'd233: begin wa=13'd1374; ch=8'h20; at=3'd0; end
            13'd234: begin wa=13'd1375; ch=8'h30; at=3'd0; end
            13'd235: begin wa=13'd1376; ch=8'h78; at=3'd0; end
            13'd236: begin wa=13'd1377; ch=hx(i2c_a0_s[7:4]); at=3'd0; end
            13'd237: begin wa=13'd1378; ch=hx(i2c_a0_s[3:0]); at=3'd0; end
            13'd238: begin wa=13'd1522; ch=8'h52; at=3'd0; end
            13'd239: begin wa=13'd1523; ch=8'h58; at=3'd0; end
            13'd240: begin wa=13'd1524; ch=8'h20; at=3'd0; end
            13'd241: begin wa=13'd1525; ch=8'h20; at=3'd0; end
            13'd242: begin wa=13'd1526; ch=8'h30; at=3'd0; end
            13'd243: begin wa=13'd1527; ch=8'h78; at=3'd0; end
            13'd244: begin wa=13'd1528; ch=hx(i2c_rx_s[7:4]); at=3'd0; end
            13'd245: begin wa=13'd1529; ch=hx(i2c_rx_s[3:0]); at=3'd0; end
            13'd246: begin wa=13'd1532; ch=8'h41; at=3'd0; end
            13'd247: begin wa=13'd1533; ch=8'h31; at=3'd0; end
            13'd248: begin wa=13'd1534; ch=8'h20; at=3'd0; end
            13'd249: begin wa=13'd1535; ch=8'h30; at=3'd0; end
            13'd250: begin wa=13'd1536; ch=8'h78; at=3'd0; end
            13'd251: begin wa=13'd1537; ch=hx(i2c_a1_s[7:4]); at=3'd0; end
            13'd252: begin wa=13'd1538; ch=hx(i2c_a1_s[3:0]); at=3'd0; end
            13'd253: begin wa=13'd1441; ch=8'h53; at=3'd2; end
            13'd254: begin wa=13'd1442; ch=8'h44; at=3'd2; end
            13'd255: begin wa=13'd1443; ch=8'h52; at=3'd2; end
            13'd256: begin wa=13'd1444; ch=8'h41; at=3'd2; end
            13'd257: begin wa=13'd1445; ch=8'h4D; at=3'd2; end
            13'd258: begin wa=13'd1446; ch=8'h20; at=3'd2; end
            13'd259: begin wa=13'd1447; ch=8'h50; at=3'd2; end
            13'd260: begin wa=13'd1448; ch=8'h52; at=3'd2; end
            13'd261: begin wa=13'd1449; ch=8'h45; at=3'd2; end
            13'd262: begin wa=13'd1450; ch=8'h4C; at=3'd2; end
            13'd263: begin wa=13'd1451; ch=8'h4F; at=3'd2; end
            13'd264: begin wa=13'd1452; ch=8'h41; at=3'd2; end
            13'd265: begin wa=13'd1453; ch=8'h44; at=3'd2; end
            13'd266: begin wa=13'd1601; ch=8'h5B; at=3'd0; end
            13'd267: begin wa=13'd1602; ch=(0 < bar32) ? "#" : "."; at=((0 < bar32) ? A_OK : 3'd7); end
            13'd268: begin wa=13'd1603; ch=(1 < bar32) ? "#" : "."; at=((1 < bar32) ? A_OK : 3'd7); end
            13'd269: begin wa=13'd1604; ch=(2 < bar32) ? "#" : "."; at=((2 < bar32) ? A_OK : 3'd7); end
            13'd270: begin wa=13'd1605; ch=(3 < bar32) ? "#" : "."; at=((3 < bar32) ? A_OK : 3'd7); end
            13'd271: begin wa=13'd1606; ch=(4 < bar32) ? "#" : "."; at=((4 < bar32) ? A_OK : 3'd7); end
            13'd272: begin wa=13'd1607; ch=(5 < bar32) ? "#" : "."; at=((5 < bar32) ? A_OK : 3'd7); end
            13'd273: begin wa=13'd1608; ch=(6 < bar32) ? "#" : "."; at=((6 < bar32) ? A_OK : 3'd7); end
            13'd274: begin wa=13'd1609; ch=(7 < bar32) ? "#" : "."; at=((7 < bar32) ? A_OK : 3'd7); end
            13'd275: begin wa=13'd1610; ch=(8 < bar32) ? "#" : "."; at=((8 < bar32) ? A_OK : 3'd7); end
            13'd276: begin wa=13'd1611; ch=(9 < bar32) ? "#" : "."; at=((9 < bar32) ? A_OK : 3'd7); end
            13'd277: begin wa=13'd1612; ch=(10 < bar32) ? "#" : "."; at=((10 < bar32) ? A_OK : 3'd7); end
            13'd278: begin wa=13'd1613; ch=(11 < bar32) ? "#" : "."; at=((11 < bar32) ? A_OK : 3'd7); end
            13'd279: begin wa=13'd1614; ch=(12 < bar32) ? "#" : "."; at=((12 < bar32) ? A_OK : 3'd7); end
            13'd280: begin wa=13'd1615; ch=(13 < bar32) ? "#" : "."; at=((13 < bar32) ? A_OK : 3'd7); end
            13'd281: begin wa=13'd1616; ch=(14 < bar32) ? "#" : "."; at=((14 < bar32) ? A_OK : 3'd7); end
            13'd282: begin wa=13'd1617; ch=(15 < bar32) ? "#" : "."; at=((15 < bar32) ? A_OK : 3'd7); end
            13'd283: begin wa=13'd1618; ch=(16 < bar32) ? "#" : "."; at=((16 < bar32) ? A_OK : 3'd7); end
            13'd284: begin wa=13'd1619; ch=(17 < bar32) ? "#" : "."; at=((17 < bar32) ? A_OK : 3'd7); end
            13'd285: begin wa=13'd1620; ch=(18 < bar32) ? "#" : "."; at=((18 < bar32) ? A_OK : 3'd7); end
            13'd286: begin wa=13'd1621; ch=(19 < bar32) ? "#" : "."; at=((19 < bar32) ? A_OK : 3'd7); end
            13'd287: begin wa=13'd1622; ch=(20 < bar32) ? "#" : "."; at=((20 < bar32) ? A_OK : 3'd7); end
            13'd288: begin wa=13'd1623; ch=(21 < bar32) ? "#" : "."; at=((21 < bar32) ? A_OK : 3'd7); end
            13'd289: begin wa=13'd1624; ch=(22 < bar32) ? "#" : "."; at=((22 < bar32) ? A_OK : 3'd7); end
            13'd290: begin wa=13'd1625; ch=(23 < bar32) ? "#" : "."; at=((23 < bar32) ? A_OK : 3'd7); end
            13'd291: begin wa=13'd1626; ch=(24 < bar32) ? "#" : "."; at=((24 < bar32) ? A_OK : 3'd7); end
            13'd292: begin wa=13'd1627; ch=(25 < bar32) ? "#" : "."; at=((25 < bar32) ? A_OK : 3'd7); end
            13'd293: begin wa=13'd1628; ch=(26 < bar32) ? "#" : "."; at=((26 < bar32) ? A_OK : 3'd7); end
            13'd294: begin wa=13'd1629; ch=(27 < bar32) ? "#" : "."; at=((27 < bar32) ? A_OK : 3'd7); end
            13'd295: begin wa=13'd1630; ch=(28 < bar32) ? "#" : "."; at=((28 < bar32) ? A_OK : 3'd7); end
            13'd296: begin wa=13'd1631; ch=(29 < bar32) ? "#" : "."; at=((29 < bar32) ? A_OK : 3'd7); end
            13'd297: begin wa=13'd1632; ch=(30 < bar32) ? "#" : "."; at=((30 < bar32) ? A_OK : 3'd7); end
            13'd298: begin wa=13'd1633; ch=(31 < bar32) ? "#" : "."; at=((31 < bar32) ? A_OK : 3'd7); end
            13'd299: begin wa=13'd1634; ch=8'h5D; at=3'd0; end
            13'd300: begin wa=13'd1636; ch=8'h50; at=3'd0; end
            13'd301: begin wa=13'd1637; ch=8'h43; at=3'd0; end
            13'd302: begin wa=13'd1638; ch=8'h54; at=3'd0; end
            13'd303: begin wa=13'd1640; ch=hx(pctd[11:8]); at=3'd1; end
            13'd304: begin wa=13'd1641; ch=hx(pctd[7:4]); at=3'd1; end
            13'd305: begin wa=13'd1642; ch=hx(pctd[3:0]); at=3'd1; end
            13'd306: begin wa=13'd1761; ch=8'h46; at=3'd0; end
            13'd307: begin wa=13'd1762; ch=8'h49; at=3'd0; end
            13'd308: begin wa=13'd1763; ch=8'h4C; at=3'd0; end
            13'd309: begin wa=13'd1764; ch=8'h4C; at=3'd0; end
            13'd310: begin wa=13'd1765; ch=8'h20; at=3'd0; end
            13'd311: begin wa=13'd1766; ch=8'h46; at=3'd0; end
            13'd312: begin wa=13'd1767; ch=8'h52; at=3'd0; end
            13'd313: begin wa=13'd1768; ch=8'h4F; at=3'd0; end
            13'd314: begin wa=13'd1769; ch=8'h4E; at=3'd0; end
            13'd315: begin wa=13'd1770; ch=8'h54; at=3'd0; end
            13'd316: begin wa=13'd1771; ch=8'h20; at=3'd0; end
            13'd317: begin wa=13'd1772; ch=8'h30; at=3'd0; end
            13'd318: begin wa=13'd1773; ch=8'h78; at=3'd0; end
            13'd319: begin wa=13'd1774; ch=hx(filled24[23:20]); at=3'd0; end
            13'd320: begin wa=13'd1775; ch=hx(filled24[19:16]); at=3'd0; end
            13'd321: begin wa=13'd1776; ch=hx(filled24[15:12]); at=3'd0; end
            13'd322: begin wa=13'd1777; ch=hx(filled24[11:8]); at=3'd0; end
            13'd323: begin wa=13'd1778; ch=hx(filled24[7:4]); at=3'd0; end
            13'd324: begin wa=13'd1779; ch=hx(filled24[3:0]); at=3'd0; end
            13'd325: begin wa=13'd1784; ch=8'h53; at=3'd0; end
            13'd326: begin wa=13'd1785; ch=8'h44; at=3'd0; end
            13'd327: begin wa=13'd1786; ch=8'h52; at=3'd0; end
            13'd328: begin wa=13'd1787; ch=8'h41; at=3'd0; end
            13'd329: begin wa=13'd1788; ch=8'h4D; at=3'd0; end
            13'd330: begin wa=13'd1790; ch=sdw[0]; at=(sda); end
            13'd331: begin wa=13'd1791; ch=sdw[1]; at=(sda); end
            13'd332: begin wa=13'd1792; ch=sdw[2]; at=(sda); end
            13'd333: begin wa=13'd1793; ch=sdw[3]; at=(sda); end
            13'd334: begin wa=13'd1794; ch=sdw[4]; at=(sda); end
            13'd335: begin wa=13'd2081; ch=8'h41; at=3'd2; end
            13'd336: begin wa=13'd2082; ch=8'h44; at=3'd2; end
            13'd337: begin wa=13'd2083; ch=8'h44; at=3'd2; end
            13'd338: begin wa=13'd2084; ch=8'h52; at=3'd2; end
            13'd339: begin wa=13'd2085; ch=8'h45; at=3'd2; end
            13'd340: begin wa=13'd2086; ch=8'h53; at=3'd2; end
            13'd341: begin wa=13'd2087; ch=8'h53; at=3'd2; end
            13'd342: begin wa=13'd2088; ch=8'h2D; at=3'd2; end
            13'd343: begin wa=13'd2089; ch=8'h53; at=3'd2; end
            13'd344: begin wa=13'd2090; ch=8'h50; at=3'd2; end
            13'd345: begin wa=13'd2091; ch=8'h41; at=3'd2; end
            13'd346: begin wa=13'd2092; ch=8'h43; at=3'd2; end
            13'd347: begin wa=13'd2093; ch=8'h45; at=3'd2; end
            13'd348: begin wa=13'd2094; ch=8'h20; at=3'd2; end
            13'd349: begin wa=13'd2095; ch=8'h53; at=3'd2; end
            13'd350: begin wa=13'd2096; ch=8'h45; at=3'd2; end
            13'd351: begin wa=13'd2097; ch=8'h52; at=3'd2; end
            13'd352: begin wa=13'd2098; ch=8'h56; at=3'd2; end
            13'd353: begin wa=13'd2099; ch=8'h45; at=3'd2; end
            13'd354: begin wa=13'd2100; ch=8'h20; at=3'd2; end
            13'd355: begin wa=13'd2101; ch=8'h4D; at=3'd2; end
            13'd356: begin wa=13'd2102; ch=8'h41; at=3'd2; end
            13'd357: begin wa=13'd2103; ch=8'h50; at=3'd2; end
            13'd358: begin wa=13'd2110; ch=8'h3E; at=3'd7; end
            13'd359: begin wa=13'd2111; ch=8'h20; at=3'd7; end
            13'd360: begin wa=13'd2112; ch=8'h72; at=3'd7; end
            13'd361: begin wa=13'd2113; ch=8'h65; at=3'd7; end
            13'd362: begin wa=13'd2114; ch=8'h61; at=3'd7; end
            13'd363: begin wa=13'd2115; ch=8'h64; at=3'd7; end
            13'd364: begin wa=13'd2116; ch=8'h20; at=3'd7; end
            13'd365: begin wa=13'd2117; ch=8'h20; at=3'd7; end
            13'd366: begin wa=13'd2118; ch=8'h23; at=3'd7; end
            13'd367: begin wa=13'd2119; ch=8'h20; at=3'd7; end
            13'd368: begin wa=13'd2120; ch=8'h73; at=3'd7; end
            13'd369: begin wa=13'd2121; ch=8'h65; at=3'd7; end
            13'd370: begin wa=13'd2122; ch=8'h72; at=3'd7; end
            13'd371: begin wa=13'd2123; ch=8'h76; at=3'd7; end
            13'd372: begin wa=13'd2124; ch=8'h65; at=3'd7; end
            13'd373: begin wa=13'd2125; ch=8'h64; at=3'd7; end
            13'd374: begin wa=13'd2126; ch=8'h20; at=3'd7; end
            13'd375: begin wa=13'd2127; ch=8'h20; at=3'd7; end
            13'd376: begin wa=13'd2128; ch=8'h2E; at=3'd7; end
            13'd377: begin wa=13'd2129; ch=8'h20; at=3'd7; end
            13'd378: begin wa=13'd2130; ch=8'h69; at=3'd7; end
            13'd379: begin wa=13'd2131; ch=8'h64; at=3'd7; end
            13'd380: begin wa=13'd2132; ch=8'h6C; at=3'd7; end
            13'd381: begin wa=13'd2133; ch=8'h65; at=3'd7; end
            13'd382: begin wa=13'd2241; ch=8'h30; at=3'd0; end
            13'd383: begin wa=13'd2242; ch=8'h78; at=3'd0; end
            13'd384: begin wa=13'd2243; ch=8'h30; at=3'd0; end
            13'd385: begin wa=13'd2244; ch=8'h30; at=3'd0; end
            13'd386: begin wa=13'd2245; ch=8'h30; at=3'd0; end
            13'd387: begin wa=13'd2246; ch=8'h30; at=3'd0; end
            13'd388: begin wa=13'd2247; ch=8'h30; at=3'd0; end
            13'd389: begin wa=13'd2248; ch=8'h30; at=3'd0; end
            13'd390: begin wa=13'd2296; ch=8'h30; at=3'd0; end
            13'd391: begin wa=13'd2297; ch=8'h78; at=3'd0; end
            13'd392: begin wa=13'd2298; ch=8'h31; at=3'd0; end
            13'd393: begin wa=13'd2299; ch=8'h46; at=3'd0; end
            13'd394: begin wa=13'd2300; ch=8'h46; at=3'd0; end
            13'd395: begin wa=13'd2301; ch=8'h46; at=3'd0; end
            13'd396: begin wa=13'd2302; ch=8'h46; at=3'd0; end
            13'd397: begin wa=13'd2303; ch=8'h46; at=3'd0; end
            13'd398: begin wa=13'd2401; ch=8'h5B; at=3'd0; end
            13'd399: begin wa=13'd2402; ch=mapch(0); at=(mapat(0)); end
            13'd400: begin wa=13'd2403; ch=mapch(1); at=(mapat(1)); end
            13'd401: begin wa=13'd2404; ch=mapch(2); at=(mapat(2)); end
            13'd402: begin wa=13'd2405; ch=mapch(3); at=(mapat(3)); end
            13'd403: begin wa=13'd2406; ch=mapch(4); at=(mapat(4)); end
            13'd404: begin wa=13'd2407; ch=mapch(5); at=(mapat(5)); end
            13'd405: begin wa=13'd2408; ch=mapch(6); at=(mapat(6)); end
            13'd406: begin wa=13'd2409; ch=mapch(7); at=(mapat(7)); end
            13'd407: begin wa=13'd2410; ch=mapch(8); at=(mapat(8)); end
            13'd408: begin wa=13'd2411; ch=mapch(9); at=(mapat(9)); end
            13'd409: begin wa=13'd2412; ch=mapch(10); at=(mapat(10)); end
            13'd410: begin wa=13'd2413; ch=mapch(11); at=(mapat(11)); end
            13'd411: begin wa=13'd2414; ch=mapch(12); at=(mapat(12)); end
            13'd412: begin wa=13'd2415; ch=mapch(13); at=(mapat(13)); end
            13'd413: begin wa=13'd2416; ch=mapch(14); at=(mapat(14)); end
            13'd414: begin wa=13'd2417; ch=mapch(15); at=(mapat(15)); end
            13'd415: begin wa=13'd2418; ch=mapch(16); at=(mapat(16)); end
            13'd416: begin wa=13'd2419; ch=mapch(17); at=(mapat(17)); end
            13'd417: begin wa=13'd2420; ch=mapch(18); at=(mapat(18)); end
            13'd418: begin wa=13'd2421; ch=mapch(19); at=(mapat(19)); end
            13'd419: begin wa=13'd2422; ch=mapch(20); at=(mapat(20)); end
            13'd420: begin wa=13'd2423; ch=mapch(21); at=(mapat(21)); end
            13'd421: begin wa=13'd2424; ch=mapch(22); at=(mapat(22)); end
            13'd422: begin wa=13'd2425; ch=mapch(23); at=(mapat(23)); end
            13'd423: begin wa=13'd2426; ch=mapch(24); at=(mapat(24)); end
            13'd424: begin wa=13'd2427; ch=mapch(25); at=(mapat(25)); end
            13'd425: begin wa=13'd2428; ch=mapch(26); at=(mapat(26)); end
            13'd426: begin wa=13'd2429; ch=mapch(27); at=(mapat(27)); end
            13'd427: begin wa=13'd2430; ch=mapch(28); at=(mapat(28)); end
            13'd428: begin wa=13'd2431; ch=mapch(29); at=(mapat(29)); end
            13'd429: begin wa=13'd2432; ch=mapch(30); at=(mapat(30)); end
            13'd430: begin wa=13'd2433; ch=mapch(31); at=(mapat(31)); end
            13'd431: begin wa=13'd2434; ch=mapch(32); at=(mapat(32)); end
            13'd432: begin wa=13'd2435; ch=mapch(33); at=(mapat(33)); end
            13'd433: begin wa=13'd2436; ch=mapch(34); at=(mapat(34)); end
            13'd434: begin wa=13'd2437; ch=mapch(35); at=(mapat(35)); end
            13'd435: begin wa=13'd2438; ch=mapch(36); at=(mapat(36)); end
            13'd436: begin wa=13'd2439; ch=mapch(37); at=(mapat(37)); end
            13'd437: begin wa=13'd2440; ch=mapch(38); at=(mapat(38)); end
            13'd438: begin wa=13'd2441; ch=mapch(39); at=(mapat(39)); end
            13'd439: begin wa=13'd2442; ch=mapch(40); at=(mapat(40)); end
            13'd440: begin wa=13'd2443; ch=mapch(41); at=(mapat(41)); end
            13'd441: begin wa=13'd2444; ch=mapch(42); at=(mapat(42)); end
            13'd442: begin wa=13'd2445; ch=mapch(43); at=(mapat(43)); end
            13'd443: begin wa=13'd2446; ch=mapch(44); at=(mapat(44)); end
            13'd444: begin wa=13'd2447; ch=mapch(45); at=(mapat(45)); end
            13'd445: begin wa=13'd2448; ch=mapch(46); at=(mapat(46)); end
            13'd446: begin wa=13'd2449; ch=mapch(47); at=(mapat(47)); end
            13'd447: begin wa=13'd2450; ch=mapch(48); at=(mapat(48)); end
            13'd448: begin wa=13'd2451; ch=mapch(49); at=(mapat(49)); end
            13'd449: begin wa=13'd2452; ch=mapch(50); at=(mapat(50)); end
            13'd450: begin wa=13'd2453; ch=mapch(51); at=(mapat(51)); end
            13'd451: begin wa=13'd2454; ch=mapch(52); at=(mapat(52)); end
            13'd452: begin wa=13'd2455; ch=mapch(53); at=(mapat(53)); end
            13'd453: begin wa=13'd2456; ch=mapch(54); at=(mapat(54)); end
            13'd454: begin wa=13'd2457; ch=mapch(55); at=(mapat(55)); end
            13'd455: begin wa=13'd2458; ch=mapch(56); at=(mapat(56)); end
            13'd456: begin wa=13'd2459; ch=mapch(57); at=(mapat(57)); end
            13'd457: begin wa=13'd2460; ch=mapch(58); at=(mapat(58)); end
            13'd458: begin wa=13'd2461; ch=mapch(59); at=(mapat(59)); end
            13'd459: begin wa=13'd2462; ch=mapch(60); at=(mapat(60)); end
            13'd460: begin wa=13'd2463; ch=mapch(61); at=(mapat(61)); end
            13'd461: begin wa=13'd2464; ch=mapch(62); at=(mapat(62)); end
            13'd462: begin wa=13'd2465; ch=mapch(63); at=(mapat(63)); end
            13'd463: begin wa=13'd2466; ch=8'h5D; at=3'd0; end
            13'd464: begin wa=13'd2562; ch=8'h42; at=3'd7; end
            13'd465: begin wa=13'd2563; ch=8'h4F; at=3'd7; end
            13'd466: begin wa=13'd2564; ch=8'h4F; at=3'd7; end
            13'd467: begin wa=13'd2565; ch=8'h54; at=3'd7; end
            13'd468: begin wa=13'd2578; ch=8'h42; at=3'd7; end
            13'd469: begin wa=13'd2579; ch=8'h41; at=3'd7; end
            13'd470: begin wa=13'd2580; ch=8'h4E; at=3'd7; end
            13'd471: begin wa=13'd2581; ch=8'h4B; at=3'd7; end
            13'd472: begin wa=13'd2582; ch=8'h53; at=3'd7; end
            13'd473: begin wa=13'd2610; ch=8'h52; at=3'd7; end
            13'd474: begin wa=13'd2611; ch=8'h53; at=3'd7; end
            13'd475: begin wa=13'd2612; ch=8'h56; at=3'd7; end
            13'd476: begin wa=13'd2881; ch=8'h53; at=3'd2; end
            13'd477: begin wa=13'd2882; ch=8'h45; at=3'd2; end
            13'd478: begin wa=13'd2883; ch=8'h52; at=3'd2; end
            13'd479: begin wa=13'd2884; ch=8'h56; at=3'd2; end
            13'd480: begin wa=13'd2885; ch=8'h45; at=3'd2; end
            13'd481: begin wa=13'd2886; ch=8'h20; at=3'd2; end
            13'd482: begin wa=13'd2887; ch=8'h4C; at=3'd2; end
            13'd483: begin wa=13'd2888; ch=8'h4F; at=3'd2; end
            13'd484: begin wa=13'd2889; ch=8'h47; at=3'd2; end
            13'd485: begin wa=13'd2894; ch=8'h61; at=3'd7; end
            13'd486: begin wa=13'd2895; ch=8'h64; at=3'd7; end
            13'd487: begin wa=13'd2896; ch=8'h64; at=3'd7; end
            13'd488: begin wa=13'd2897; ch=8'h72; at=3'd7; end
            13'd489: begin wa=13'd2898; ch=8'h20; at=3'd7; end
            13'd490: begin wa=13'd2899; ch=8'h3A; at=3'd7; end
            13'd491: begin wa=13'd2900; ch=8'h20; at=3'd7; end
            13'd492: begin wa=13'd2901; ch=8'h62; at=3'd7; end
            13'd493: begin wa=13'd2902; ch=8'h79; at=3'd7; end
            13'd494: begin wa=13'd2903; ch=8'h74; at=3'd7; end
            13'd495: begin wa=13'd2904; ch=8'h65; at=3'd7; end
            13'd496: begin wa=13'd3041; ch=hx(log0a[19:16]); at=3'd0; end
            13'd497: begin wa=13'd3042; ch=hx(log0a[15:12]); at=3'd0; end
            13'd498: begin wa=13'd3043; ch=hx(log0a[11:8]); at=3'd0; end
            13'd499: begin wa=13'd3044; ch=hx(log0a[7:4]); at=3'd0; end
            13'd500: begin wa=13'd3045; ch=hx(log0a[3:0]); at=3'd0; end
            13'd501: begin wa=13'd3046; ch=8'h3A; at=3'd0; end
            13'd502: begin wa=13'd3047; ch=hx(log0b[7:4]); at=3'd3; end
            13'd503: begin wa=13'd3048; ch=hx(log0b[3:0]); at=3'd3; end
            13'd504: begin wa=13'd3201; ch=hx(log1a[19:16]); at=3'd0; end
            13'd505: begin wa=13'd3202; ch=hx(log1a[15:12]); at=3'd0; end
            13'd506: begin wa=13'd3203; ch=hx(log1a[11:8]); at=3'd0; end
            13'd507: begin wa=13'd3204; ch=hx(log1a[7:4]); at=3'd0; end
            13'd508: begin wa=13'd3205; ch=hx(log1a[3:0]); at=3'd0; end
            13'd509: begin wa=13'd3206; ch=8'h3A; at=3'd0; end
            13'd510: begin wa=13'd3207; ch=hx(log1b[7:4]); at=3'd3; end
            13'd511: begin wa=13'd3208; ch=hx(log1b[3:0]); at=3'd3; end
            13'd512: begin wa=13'd3361; ch=hx(log2a[19:16]); at=3'd0; end
            13'd513: begin wa=13'd3362; ch=hx(log2a[15:12]); at=3'd0; end
            13'd514: begin wa=13'd3363; ch=hx(log2a[11:8]); at=3'd0; end
            13'd515: begin wa=13'd3364; ch=hx(log2a[7:4]); at=3'd0; end
            13'd516: begin wa=13'd3365; ch=hx(log2a[3:0]); at=3'd0; end
            13'd517: begin wa=13'd3366; ch=8'h3A; at=3'd0; end
            13'd518: begin wa=13'd3367; ch=hx(log2b[7:4]); at=3'd3; end
            13'd519: begin wa=13'd3368; ch=hx(log2b[3:0]); at=3'd3; end
            13'd520: begin wa=13'd3521; ch=hx(log3a[19:16]); at=3'd0; end
            13'd521: begin wa=13'd3522; ch=hx(log3a[15:12]); at=3'd0; end
            13'd522: begin wa=13'd3523; ch=hx(log3a[11:8]); at=3'd0; end
            13'd523: begin wa=13'd3524; ch=hx(log3a[7:4]); at=3'd0; end
            13'd524: begin wa=13'd3525; ch=hx(log3a[3:0]); at=3'd0; end
            13'd525: begin wa=13'd3526; ch=8'h3A; at=3'd0; end
            13'd526: begin wa=13'd3527; ch=hx(log3b[7:4]); at=3'd3; end
            13'd527: begin wa=13'd3528; ch=hx(log3b[3:0]); at=3'd3; end
            13'd528: begin wa=13'd3681; ch=hx(log4a[19:16]); at=3'd0; end
            13'd529: begin wa=13'd3682; ch=hx(log4a[15:12]); at=3'd0; end
            13'd530: begin wa=13'd3683; ch=hx(log4a[11:8]); at=3'd0; end
            13'd531: begin wa=13'd3684; ch=hx(log4a[7:4]); at=3'd0; end
            13'd532: begin wa=13'd3685; ch=hx(log4a[3:0]); at=3'd0; end
            13'd533: begin wa=13'd3686; ch=8'h3A; at=3'd0; end
            13'd534: begin wa=13'd3687; ch=hx(log4b[7:4]); at=3'd3; end
            13'd535: begin wa=13'd3688; ch=hx(log4b[3:0]); at=3'd3; end
            13'd536: begin wa=13'd3841; ch=hx(log5a[19:16]); at=3'd0; end
            13'd537: begin wa=13'd3842; ch=hx(log5a[15:12]); at=3'd0; end
            13'd538: begin wa=13'd3843; ch=hx(log5a[11:8]); at=3'd0; end
            13'd539: begin wa=13'd3844; ch=hx(log5a[7:4]); at=3'd0; end
            13'd540: begin wa=13'd3845; ch=hx(log5a[3:0]); at=3'd0; end
            13'd541: begin wa=13'd3846; ch=8'h3A; at=3'd0; end
            13'd542: begin wa=13'd3847; ch=hx(log5b[7:4]); at=3'd3; end
            13'd543: begin wa=13'd3848; ch=hx(log5b[3:0]); at=3'd3; end
            13'd544: begin wa=13'd4001; ch=hx(log6a[19:16]); at=3'd0; end
            13'd545: begin wa=13'd4002; ch=hx(log6a[15:12]); at=3'd0; end
            13'd546: begin wa=13'd4003; ch=hx(log6a[11:8]); at=3'd0; end
            13'd547: begin wa=13'd4004; ch=hx(log6a[7:4]); at=3'd0; end
            13'd548: begin wa=13'd4005; ch=hx(log6a[3:0]); at=3'd0; end
            13'd549: begin wa=13'd4006; ch=8'h3A; at=3'd0; end
            13'd550: begin wa=13'd4007; ch=hx(log6b[7:4]); at=3'd3; end
            13'd551: begin wa=13'd4008; ch=hx(log6b[3:0]); at=3'd3; end
            13'd552: begin wa=13'd4161; ch=hx(log7a[19:16]); at=3'd0; end
            13'd553: begin wa=13'd4162; ch=hx(log7a[15:12]); at=3'd0; end
            13'd554: begin wa=13'd4163; ch=hx(log7a[11:8]); at=3'd0; end
            13'd555: begin wa=13'd4164; ch=hx(log7a[7:4]); at=3'd0; end
            13'd556: begin wa=13'd4165; ch=hx(log7a[3:0]); at=3'd0; end
            13'd557: begin wa=13'd4166; ch=8'h3A; at=3'd0; end
            13'd558: begin wa=13'd4167; ch=hx(log7b[7:4]); at=3'd3; end
            13'd559: begin wa=13'd4168; ch=hx(log7b[3:0]); at=3'd3; end
            13'd560: begin wa=13'd2920; ch=8'h53; at=3'd2; end
            13'd561: begin wa=13'd2921; ch=8'h54; at=3'd2; end
            13'd562: begin wa=13'd2922; ch=8'h41; at=3'd2; end
            13'd563: begin wa=13'd2923; ch=8'h42; at=3'd2; end
            13'd564: begin wa=13'd2924; ch=8'h49; at=3'd2; end
            13'd565: begin wa=13'd2925; ch=8'h4C; at=3'd2; end
            13'd566: begin wa=13'd2926; ch=8'h49; at=3'd2; end
            13'd567: begin wa=13'd2927; ch=8'h54; at=3'd2; end
            13'd568: begin wa=13'd2928; ch=8'h59; at=3'd2; end
            13'd569: begin wa=13'd3080; ch=8'h52; at=3'd0; end
            13'd570: begin wa=13'd3081; ch=8'h45; at=3'd0; end
            13'd571: begin wa=13'd3082; ch=8'h53; at=3'd0; end
            13'd572: begin wa=13'd3083; ch=8'h45; at=3'd0; end
            13'd573: begin wa=13'd3084; ch=8'h54; at=3'd0; end
            13'd574: begin wa=13'd3085; ch=8'h53; at=3'd0; end
            13'd575: begin wa=13'd3087; ch=hx(resets[11:8]); at=3'd0; end
            13'd576: begin wa=13'd3088; ch=hx(resets[7:4]); at=3'd0; end
            13'd577: begin wa=13'd3089; ch=hx(resets[3:0]); at=3'd0; end
            13'd578: begin wa=13'd3240; ch=8'h53; at=3'd0; end
            13'd579: begin wa=13'd3241; ch=8'h54; at=3'd0; end
            13'd580: begin wa=13'd3242; ch=8'h41; at=3'd0; end
            13'd581: begin wa=13'd3243; ch=8'h54; at=3'd0; end
            13'd582: begin wa=13'd3244; ch=8'h45; at=3'd0; end
            13'd583: begin wa=13'd3247; ch=fch(0); at=(fat); end
            13'd584: begin wa=13'd3248; ch=fch(1); at=(fat); end
            13'd585: begin wa=13'd3249; ch=fch(2); at=(fat); end
            13'd586: begin wa=13'd3250; ch=fch(3); at=(fat); end
            13'd587: begin wa=13'd3251; ch=fch(4); at=(fat); end
            13'd588: begin wa=13'd3252; ch=fch(5); at=(fat); end
            13'd589: begin wa=13'd3400; ch=8'h4C; at=3'd0; end
            13'd590: begin wa=13'd3401; ch=8'h41; at=3'd0; end
            13'd591: begin wa=13'd3402; ch=8'h53; at=3'd0; end
            13'd592: begin wa=13'd3403; ch=8'h54; at=3'd0; end
            13'd593: begin wa=13'd3404; ch=8'h20; at=3'd0; end
            13'd594: begin wa=13'd3405; ch=8'h46; at=3'd0; end
            13'd595: begin wa=13'd3406; ch=8'h41; at=3'd0; end
            13'd596: begin wa=13'd3407; ch=8'h55; at=3'd0; end
            13'd597: begin wa=13'd3408; ch=8'h4C; at=3'd0; end
            13'd598: begin wa=13'd3409; ch=8'h54; at=3'd0; end
            13'd599: begin wa=13'd3410; ch=8'h20; at=3'd0; end
            13'd600: begin wa=13'd3411; ch=8'h30; at=3'd0; end
            13'd601: begin wa=13'd3412; ch=8'h78; at=3'd0; end
            13'd602: begin wa=13'd3413; ch=hx(faila[19:16]); at=3'd5; end
            13'd603: begin wa=13'd3414; ch=hx(faila[15:12]); at=3'd5; end
            13'd604: begin wa=13'd3415; ch=hx(faila[11:8]); at=3'd5; end
            13'd605: begin wa=13'd3416; ch=hx(faila[7:4]); at=3'd5; end
            13'd606: begin wa=13'd3417; ch=hx(faila[3:0]); at=3'd5; end
            default: begin wa=13'd0; ch=8'h20; at=3'd0; end
        endcase
        wr_addr<=wa; wr_data<=ch; wr_attr<=at;
        idx <= (idx==13'd606) ? 13'd0 : idx+1'b1;
    end
endmodule