#!/usr/bin/env python3
# gen_hud.py -- generates the condensed EOS serve-HUD dashboard.
#
# Emits four files into the current directory (or --out dir):
#     eos_screen.hex          static char layer  (7200 cells, one byte each)
#     eos_attr.hex            static attr layer  (7200 cells, one nibble each)
#     eos_hud_microcode.hex   dynamic cells      (256 x 32-bit microcode words)
#     eos_serve_hud.v         the module (decoder + capture) matching the above
#
# Design vs. the old generator:
#   * Static text lives in the char/attr buffers' power-on image (BSRAM, 0 LUTs).
#     Only DYNAMIC cells are scanned from microcode through a shared decoder.
#   * Decoder kinds consolidated to 5: HEX / STR / BOOL / VER / BAR (was 16).
#       - HK_BOOL  absorbs mode16, abort, flash-busy, i2c-sel, hd pll/bios/en, guard
#       - HK_STR   absorbs the D0 / LRESET / SDRAM / flash-op word fields
#   * Developer telemetry removed to free LUTs + registers:
#       - serve log (8-deep last-reads)   -> ~224 FF + 8-way mux + shift chain
#       - address-space serve map (64)    -> 64-bit visited reg + map funcs
#       - serve-rate meter                -> wtick/rate counters + subtract
#       - stability panel (resets/fault)  -> lreset-fall detector + fault word
#   * Vanity banner ("Team Resurgent / Darkone83") removed.
#
# Microcode word (MSB..LSB):
#     [31:19] framebuffer address (row*160 + col)
#     [18:14] kind
#     [13:6]  arg
#     [5:3]   attr   (used by HK_HEX only; other kinds derive their own)
#     [2:0]   reserved (0)

import sys, os

COLS, ROWS = 160, 45
DEPTH = COLS * ROWS                     # 7200

# ---- encodings (MUST match the Verilog decoder emitted below) --------------
HK_HEX, HK_STR, HK_BOOL, HK_VER, HK_BAR, HK_NOP = 0, 1, 2, 3, 4, 31

SRC = {  # hex sources: arg = (SRC<<3) | nibble
    "abort_count": 0, "bank_load": 1, "bank_sel": 2, "state": 3, "rdcnt": 4,
    "addr": 5, "sbyte": 6, "iaddr": 7, "icmd": 8, "ia0": 9, "ia1": 10,
    "irx": 11, "hd_encoder": 12, "pctd": 13, "filled24": 14,
}
STRID = {"d0": 0, "lr": 1, "sd": 2, "fop": 3}          # arg = (STRID<<3) | idx
BOOLID = {"mode16": 0, "abort": 1, "fbusy": 2, "i2csel": 3,
          "pll": 4, "bios": 5, "transport": 6, "guard": 7}  # arg = BOOLID

# ---- Verilog module template (decoder + capture) ---------------------------
MODULE_V = r'''// eos_serve_hud.v -- GENERATED by gen_hud.py.  Condensed colour serve dashboard.
// __NCELLS__ dynamic cells scanned from eos_hud_microcode.hex; static text is the
// power-on image of eos_char_buffer/eos_attr_buffer (eos_screen.hex/eos_attr.hex).
// attr: 0 norm 1 hdr 2 purple 3 grn 4 amb 5 red 7 dim.
// Decoder kinds: HEX / STR / BOOL / VER / BAR (+ NOP pad).  Telemetry panels
// (serve log / serve map / rate / stability) and the vanity banner were removed
// to reclaim LUTs and registers.
module eos_serve_hud (
    input  wire        lclk, lreset_n, vclk,
    input  wire [3:0]  state,
    input  wire [20:0] mem_addr,
    input  wire [3:0]  lad,
    input  wire        sd_ready,
    input  wire        preload_done,
    input  wire [22:0] filled_lo,
    input  wire [3:0]  bank_sel,
    input  wire [2:0]  flash_op,
    input  wire        mode_16,
    input  wire        d0_active,
    input  wire        abort_active,
    input  wire [15:0] abort_count,
    input  wire [7:0]  i2c_addr,
    input  wire [7:0]  i2c_vmaj, i2c_vmin, i2c_vpat,
    input  wire [7:0]  i2c_cmd, i2c_a0, i2c_a1,
    input  wire [7:0]  i2c_rx,
    input  wire        i2c_sel,
    input  wire [3:0]  hd_encoder,
    input  wire        hd_pll_lock,
    input  wire        hd_bios_active,
    input  wire        hd_guard_blocked,
    input  wire        hd_transport_en,
    input  wire [7:0]  hd_brst,          // reserved (unused in condensed HUD)
    input  wire [7:0]  hd_dr,            // reserved (unused in condensed HUD)
    output reg         wr_en,
    output reg  [12:0] wr_addr,
    output reg  [7:0]  wr_data,
    output reg  [2:0]  wr_attr
);
    localparam [2:0] A_OK=3'd3, A_WARN=3'd4, A_FAIL=3'd5;
    localparam READ_DATA0=4'd7, READ_DATA1=4'd8, TAR_EXIT=4'd9, SYNCING=4'd5;
    function [7:0] hx; input [3:0] n; hx=(n<10)?(8'h30+n):(8'h37+n); endfunction

    // ---- sync straps/flags into lclk ----
    reg [1:0] m16_s=0,d0_s=0,ab_s=0,sdr_s=0,pld_s=0; reg [4:0] fl_s0=0,fl_s1=0;
    always @(posedge lclk) begin
        m16_s<={m16_s[0],mode_16}; d0_s<={d0_s[0],d0_active}; ab_s<={ab_s[0],abort_active};
        sdr_s<={sdr_s[0],sd_ready}; pld_s<={pld_s[0],preload_done};
        fl_s0<=filled_lo[18:14]; fl_s1<=fl_s0;
    end
    wire mode16_s=m16_s[1], d0on_s=d0_s[1], aborting_s=ab_s[1], sd_rdy=sdr_s[1], pld=pld_s[1];

    // ---- I2C engine signals -> vclk ----
    reg [7:0] iaddr=0,ivmaj=0,ivmin=0,ivpat=0,icmd=0,ia0=0,ia1=0,irx=0; reg [1:0] isel=0;
    always @(posedge vclk) begin
        iaddr<=i2c_addr; ivmaj<=i2c_vmaj; ivmin<=i2c_vmin; ivpat<=i2c_vpat;
        icmd<=i2c_cmd; ia0<=i2c_a0; ia1<=i2c_a1; irx<=i2c_rx; isel<={isel[0],i2c_sel};
    end
    wire i2c_sel_s=isel[1];

    // ---- serve capture (lclk): last addr / byte / read count / bank ----
    reg [3:0] prev_state=0, lo_nib=0; reg [7:0] sbyte=0; reg [15:0] rdcnt=0;
    reg [20:0] addr=0; reg [3:0] bank_load=4'h1; reg loaded_cap=0;
    always @(posedge lclk) begin
        if (!loaded_cap) begin bank_load<=bank_sel; loaded_cap<=1'b1; end
        prev_state<=state;
        if (state==SYNCING)    addr<=mem_addr;
        if (state==READ_DATA0) lo_nib<=lad;
        if (state==READ_DATA1) sbyte<={lad,lo_nib};
        if (prev_state==READ_DATA1 && state==TAR_EXIT) rdcnt<=rdcnt+1'b1;
    end

    // ---- preload bar + percent ----
    wire [23:0] filled24={1'b0,filled_lo};
    wire [18:0] filled_val={fl_s1,14'd0};
    wire [18:0] prog = pld ? 19'h40000 : (19'h40000 - filled_val);
    wire [5:0]  bar32 = pld ? 6'd32 : {1'b0,prog[17:13]};
    wire [25:0] prog100 = prog * 26'd100;
    wire [6:0]  pctv = pld ? 7'd100 : prog100[24:18];
    wire [3:0]  pd_h = (pctv>=7'd100)?4'd1:4'd0;
    wire [6:0]  pr1  = (pctv>=7'd100)?(pctv-7'd100):pctv;
    wire [6:0]  pd_t7= pr1/7'd10, pd_o7=pr1%7'd10;
    wire [3:0]  pd_t=pd_t7[3:0], pd_o=pd_o7[3:0];
    wire [11:0] pctd={pd_h,pd_t,pd_o};

    // ---- dynamic word fields (indexed by HK_STR) ----
    wire [7:0] d0w[0:7];
    assign d0w[0]=d0on_s?"F":"R"; assign d0w[1]=d0on_s?"O":"E"; assign d0w[2]=d0on_s?"R":"L";
    assign d0w[3]=d0on_s?"C":" "; assign d0w[4]=d0on_s?"E":" "; assign d0w[5]=d0on_s?"D":" ";
    assign d0w[6]=" "; assign d0w[7]=" ";
    wire [2:0] d0a=d0on_s?A_OK:3'd7;
    wire [7:0] lrw[0:7];
    assign lrw[0]="R"; assign lrw[1]=lreset_n?"U":"S"; assign lrw[2]=lreset_n?"N":"T";
    assign lrw[3]=" "; assign lrw[4]=" "; assign lrw[5]=" "; assign lrw[6]=" "; assign lrw[7]=" ";
    wire [2:0] lra=lreset_n?A_OK:A_FAIL;
    wire [7:0] sdw[0:7];
    assign sdw[0]=sd_rdy?"R":"W"; assign sdw[1]=sd_rdy?"D":"A"; assign sdw[2]=sd_rdy?"Y":"I";
    assign sdw[3]=sd_rdy?" ":"T"; assign sdw[4]=" "; assign sdw[5]=" "; assign sdw[6]=" "; assign sdw[7]=" ";
    wire [2:0] sda=sd_rdy?A_OK:A_WARN;
    // flash-op name as continuous assigns (kept live in sim like the other
    // string fields; synthesises to the same combinational mux).
    // IDLE / ERASE / WRITE / READ / SYNC
    wire [7:0] fopw[0:7];
    assign fopw[0]=(flash_op==3'd1)?"E":(flash_op==3'd2)?"W":(flash_op==3'd3)?"R":(flash_op==3'd4)?"S":"I";
    assign fopw[1]=(flash_op==3'd1)?"R":(flash_op==3'd2)?"R":(flash_op==3'd3)?"E":(flash_op==3'd4)?"Y":"D";
    assign fopw[2]=(flash_op==3'd1)?"A":(flash_op==3'd2)?"I":(flash_op==3'd3)?"A":(flash_op==3'd4)?"N":"L";
    assign fopw[3]=(flash_op==3'd1)?"S":(flash_op==3'd2)?"T":(flash_op==3'd3)?"D":(flash_op==3'd4)?"C":"E";
    assign fopw[4]=(flash_op==3'd1)?"E":(flash_op==3'd2)?"E":" ";
    assign fopw[5]=" "; assign fopw[6]=" "; assign fopw[7]=" ";
    wire       fbusy = (flash_op!=3'd0);
    wire [2:0] fopa  = (flash_op==3'd1||flash_op==3'd2)?A_WARN:(flash_op==3'd3)?A_OK:(flash_op==3'd4)?3'd2:3'd7;

    // ---- microcode ROM (synchronous, block_ram) ----
    localparam [4:0] HK_HEX=5'd0, HK_STR=5'd1, HK_BOOL=5'd2, HK_VER=5'd3, HK_BAR=5'd4, HK_NOP=5'd31;
    (* syn_romstyle = "block_ram" *) reg [31:0] hud_micro [0:255];
    initial $readmemh("eos_hud_microcode.hex", hud_micro);
    reg [7:0]  hud_rom_addr = 8'd0;
    reg [31:0] hud_rom_q    = 32'd0;
    reg        hud_rom_valid= 1'b0;
    wire [12:0] mc_addr = hud_rom_q[31:19];
    wire [4:0]  mc_kind = hud_rom_q[18:14];
    wire [7:0]  mc_arg  = hud_rom_q[13:6];
    wire [2:0]  mc_attr = hud_rom_q[5:3];

    // hex source mux: arg[7:3]=source, arg[2:0]=nibble
    reg [23:0] hx_bus; reg [3:0] hx_nib;
    always @(*) begin
        case (mc_arg[7:3])
            5'd0:  hx_bus = {8'd0, abort_count};
            5'd1:  hx_bus = {20'd0, bank_load};
            5'd2:  hx_bus = {20'd0, bank_sel};
            5'd3:  hx_bus = {20'd0, state};
            5'd4:  hx_bus = {8'd0, rdcnt};
            5'd5:  hx_bus = {3'd0, addr};
            5'd6:  hx_bus = {16'd0, sbyte};
            5'd7:  hx_bus = {16'd0, iaddr};
            5'd8:  hx_bus = {16'd0, icmd};
            5'd9:  hx_bus = {16'd0, ia0};
            5'd10: hx_bus = {16'd0, ia1};
            5'd11: hx_bus = {16'd0, irx};
            5'd12: hx_bus = {20'd0, hd_encoder};
            5'd13: hx_bus = {12'd0, pctd};
            5'd14: hx_bus = filled24;
            default: hx_bus = 24'd0;
        endcase
        case (mc_arg[2:0])
            3'd0: hx_nib = hx_bus[3:0];
            3'd1: hx_nib = hx_bus[7:4];
            3'd2: hx_nib = hx_bus[11:8];
            3'd3: hx_nib = hx_bus[15:12];
            3'd4: hx_nib = hx_bus[19:16];
            default: hx_nib = hx_bus[23:20];
        endcase
    end

    // STR select: arg[4:3]=field, arg[2:0]=char index
    reg [7:0] str_ch; reg [2:0] str_at;
    always @(*) begin
        case (mc_arg[4:3])
            2'd0: begin str_ch=d0w[mc_arg[2:0]]; str_at=d0a; end
            2'd1: begin str_ch=lrw[mc_arg[2:0]]; str_at=lra; end
            2'd2: begin str_ch=sdw[mc_arg[2:0]]; str_at=sda; end
            default: begin str_ch=fopw[mc_arg[2:0]]; str_at=fopa; end
        endcase
    end

    // BOOL select: arg[3:0]=flag id -> (value, true/false glyph + attr)
    reg boolv; reg [7:0] bcT,bcF; reg [2:0] baT,baF;
    always @(*) begin
        case (mc_arg[3:0])
            4'd0: begin boolv=mode16_s;        bcT="6"; bcF="5"; baT=A_WARN; baF=A_OK;  end
            4'd1: begin boolv=aborting_s;      bcT="*"; bcF=" "; baT=A_FAIL; baF=A_FAIL;end
            4'd2: begin boolv=fbusy;           bcT="Y"; bcF="-"; baT=A_WARN; baF=3'd7;  end
            4'd3: begin boolv=i2c_sel_s;       bcT="*"; bcF="-"; baT=A_OK;   baF=3'd7;  end
            4'd4: begin boolv=hd_pll_lock;     bcT="Y"; bcF="-"; baT=A_OK;   baF=3'd7;  end
            4'd5: begin boolv=hd_bios_active;  bcT="Y"; bcF="-"; baT=A_OK;   baF=3'd7;  end
            4'd6: begin boolv=hd_transport_en; bcT="Y"; bcF="-"; baT=A_OK;   baF=3'd7;  end
            default: begin boolv=hd_guard_blocked; bcT="B"; bcF="A"; baT=A_WARN; baF=A_OK; end
        endcase
    end

    // shared kind decoder
    reg [7:0] hud_ch; reg [2:0] hud_at; reg wr_gate;
    always @(*) begin
        hud_ch=8'h20; hud_at=mc_attr; wr_gate=1'b1;
        case (mc_kind)
            HK_HEX:  begin hud_ch=hx(hx_nib); hud_at=mc_attr; end
            HK_STR:  begin hud_ch=str_ch;     hud_at=str_at; end
            HK_BOOL: begin hud_ch=boolv?bcT:bcF; hud_at=boolv?baT:baF; end
            HK_VER:  begin
                case (mc_arg[1:0])
                    2'd0: hud_ch=8'h30+ivmaj;
                    2'd1: hud_ch=8'h30+ivmin;
                    default: hud_ch=8'h30+ivpat;
                endcase
                hud_at=3'd0;
            end
            HK_BAR:  begin hud_ch=(mc_arg[5:0]<bar32)?"#":"."; hud_at=(mc_arg[5:0]<bar32)?A_OK:3'd7; end
            default: wr_gate=1'b0;                                  // HK_NOP -> skip write
        endcase
    end

    // scan FSM: one microcode cell per vclk; 8-bit addr wraps the full 256-word ROM.
    always @(posedge vclk) begin
        hud_rom_q    <= hud_micro[hud_rom_addr];
        hud_rom_addr <= hud_rom_addr + 1'b1;
        wr_en <= hud_rom_valid & wr_gate;
        if (hud_rom_valid & wr_gate) begin
            wr_addr <= mc_addr;
            wr_data <= hud_ch;
            wr_attr <= hud_at;
        end
        hud_rom_valid <= 1'b1;
    end
endmodule
'''

# ---- cell collection -------------------------------------------------------
static = {}     # wa -> (char, attr)
micro  = []     # (wa, kind, arg, attr)

def _wa(r, c):
    if not (0 <= r < ROWS and 0 <= c < COLS):
        raise SystemExit("ERROR: cell out of grid at row %d col %d" % (r, c))
    return r * COLS + c

def T(r, c, s, at=0):                                  # static text
    for i, ch in enumerate(s):
        static[_wa(r, c + i)] = (ord(ch), at)

def HX(r, c, src, hi, lo, at=0):                       # hex nibbles, MSB first
    sid = SRC[src]
    for k in range(hi, lo - 1, -1):
        micro.append((_wa(r, c + (hi - k)), HK_HEX, (sid << 3) | k, at))

def STRF(r, c, strid, length):                         # dynamic word field
    sid = STRID[strid]
    for i in range(length):
        micro.append((_wa(r, c + i), HK_STR, (sid << 3) | i, 0))

def BOOL(r, c, name):                                  # boolean glyph
    micro.append((_wa(r, c), HK_BOOL, BOOLID[name], 0))

def VER(r, c, which):                                  # version digit 0/1/2
    micro.append((_wa(r, c), HK_VER, which & 0x3, 0))

def BAR(r, c, i):                                      # preload bar segment
    micro.append((_wa(r, c), HK_BAR, i & 0x3F, 0))

# ---- layout ----------------------------------------------------------------
T(0, 1, " EOS  LPC BIOS SERVER ", 1)

# BOOT / LINK
T(2, 1, "BOOT / LINK", 2)
T(3, 1, "REV"); T(3, 7, "1.", 2); BOOL(3, 9, "mode16")
T(4, 1, "D0");  STRF(4, 7, "d0", 6)
T(5, 1, "LFRAME ABORTS"); HX(5, 15, "abort_count", 3, 0, 4); BOOL(5, 20, "abort")
T(6, 1, "LCLK");   T(6, 7, "[ OK ]", 3)
T(7, 1, "LRESET"); STRF(7, 7, "lr", 5)

# SERVE
T(2, 40, "SERVE", 2)
T(3, 40, "BANK");  HX(3, 46, "bank_load", 0, 0, 3); T(3, 47, "/"); HX(3, 48, "bank_sel", 0, 0, 1)
T(4, 40, "STATE"); HX(4, 46, "state", 0, 0, 0)
T(5, 40, "READS"); HX(5, 46, "rdcnt", 3, 0, 0)
T(6, 40, "LAST");  HX(6, 46, "addr", 4, 0, 2); T(6, 51, ":"); HX(6, 52, "sbyte", 1, 0, 1)

# FLASH ENGINE
T(2, 82, "FLASH ENGINE", 2)
T(3, 82, "OP");   STRF(3, 88, "fop", 5)
T(4, 82, "BUSY"); BOOL(4, 88, "fbusy")

# I2C ENGINE (SMBus slave, addr 0xDC)
T(6, 82, "I2C ENGINE", 2)
T(6, 100, "SEL"); BOOL(6, 104, "i2csel")
T(7, 82, "ADDR 0x"); HX(7, 89, "iaddr", 1, 0, 0)
T(7, 94, "VER "); VER(7, 98, 0); T(7, 99, "."); VER(7, 100, 1); T(7, 101, "."); VER(7, 102, 2)
T(8, 82, "CMD 0x"); HX(8, 88, "icmd", 1, 0, 3)
T(8, 92, "A0 0x");  HX(8, 97, "ia0", 1, 0, 0)
T(9, 82, "RX  0x"); HX(9, 88, "irx", 1, 0, 0)
T(9, 92, "A1 0x");  HX(9, 97, "ia1", 1, 0, 0)

# HD STATUS (reserved until eos_hd.v lands; top ties off to "not installed")
T(2, 110, "HD STATUS", 2)
T(3, 110, "ENC");  HX(3, 114, "hd_encoder", 0, 0, 0)
T(3, 118, "PLL");  BOOL(3, 122, "pll")
T(4, 110, "BIOS"); BOOL(4, 115, "bios")
T(4, 118, "GRD");  BOOL(4, 122, "guard")
T(5, 110, "EN");   BOOL(5, 113, "transport")

# SDRAM PRELOAD
T(9, 1, "SDRAM PRELOAD", 2)
T(10, 1, "[")
for i in range(32):
    BAR(10, 2 + i, i)
T(10, 34, "]")
T(10, 36, "PCT"); HX(10, 40, "pctd", 2, 0, 1)
T(11, 1, "FILL FRONT 0x"); HX(11, 14, "filled24", 5, 0, 0)
T(11, 24, "SDRAM"); STRF(11, 30, "sd", 5)

# ---- checks ----------------------------------------------------------------
seen = set()
for (wa, k, a, at) in micro:
    if wa in static:
        print("note: dynamic cell overwrites static at wa=%d" % wa, file=sys.stderr)
    if wa in seen:
        print("note: duplicate dynamic cell at wa=%d" % wa, file=sys.stderr)
    seen.add(wa)
N = len(micro)
if N > 256:
    raise SystemExit("ERROR: %d dynamic cells exceeds 256-word microcode ROM" % N)

# ---- emit hex --------------------------------------------------------------
def emit(path, lines):
    with open(path, "w", newline="\n") as f:
        f.write("\n".join(lines) + "\n")

outdir = "."
if len(sys.argv) > 1:
    outdir = sys.argv[1]
os.makedirs(outdir, exist_ok=True)

scr = ["20"] * DEPTH          # default blank space
att = ["0"] * DEPTH           # default NORMAL
for wa, (ch, at) in static.items():
    scr[wa] = "%02X" % ch
    att[wa] = "%X" % (at & 0x7)
emit(os.path.join(outdir, "eos_screen.hex"), scr)
emit(os.path.join(outdir, "eos_attr.hex"), att)

mc = []
for (wa, k, a, at) in micro:
    word = ((wa & 0x1FFF) << 19) | ((k & 0x1F) << 14) | ((a & 0xFF) << 6) | ((at & 0x7) << 3)
    mc.append("%08X" % word)
nop = "%08X" % ((HK_NOP & 0x1F) << 14)     # kind=NOP, wr suppressed
while len(mc) < 256:
    mc.append(nop)
emit(os.path.join(outdir, "eos_hud_microcode.hex"), mc)

# ---- emit module -----------------------------------------------------------
emit(os.path.join(outdir, "eos_serve_hud.v"), [MODULE_V.replace("__NCELLS__", str(N))])
print("generated: eos_screen.hex eos_attr.hex eos_hud_microcode.hex eos_serve_hud.v"
      "  (%d dynamic cells, %d static cells)" % (N, len(static)))
